;;; masu-emojis.el --- Custom emoji insertion -*- lexical-binding: t; -*-

;;; Commentary:
;; Provides a simple emoji picker that bypasses emojify's display issues.
;; All unicode emojis from emacs-emojify plus custom additions.

;;; Code:

(defvar masu/custom-emojis
  '(
    ("🏳️‍⚧️ transgender flag / trans" . "🏳️‍⚧️")
    ("🏳️‍🌈 pride flag / rainbow / gay" . "🏳️‍🌈")
    ("🐄💩 bullshit / bull-shit" . "🐄💩")
    ("😠 mad / angry / pissed" . "😠")

    ;; alphabetical ones
    ("🎟 admission tickets" . "🎟")
    ("🚡 aerial tramway" . "🚡")
    ("🇦🇫 afghanistan" . "🇦🇫")
    ("✈ airplane" . "✈")
    ("🛬 airplane arriving" . "🛬")
    ("🛫 airplane departure" . "🛫")
    ("⏰ alarm clock" . "⏰")
    ("🇦🇱 albania" . "🇦🇱")
    ("⚗ alembic" . "⚗")
    ("🇩🇿 algeria" . "🇩🇿")
    ("👾 alien monster" . "👾")
    ("🚑 ambulance" . "🚑")
    ("🏈 american football" . "🏈")
    ("🇦🇸 american samoa" . "🇦🇸")
    ("🏺 amphora" . "🏺")
    ("⚓ anchor" . "⚓")
    ("🇦🇩 andorra" . "🇦🇩")
    ("💢 anger symbol" . "💢")
    ("🇦🇴 angola" . "🇦🇴")
    ("😠 angry face" . "😠")
    ("🇦🇮 anguilla" . "🇦🇮")
    ("😧 anguished face" . "😧")
    ("🐜 ant" . "🐜")
    ("🇦🇶 antarctica" . "🇦🇶")
    ("📶 antenna with bars" . "📶")
    ("🔄 anticlockwise downwards and upwards open circle arrows" . "🔄")
    ("🇦🇬 antigua and barbuda" . "🇦🇬")
    ("♒ aquarius" . "♒")
    ("🇦🇷 argentina" . "🇦🇷")
    ("♈ aries" . "♈")
    ("🇦🇲 armenia" . "🇦🇲")
    ("⤵ arrow pointing rightwards then curving downwards" . "⤵")
    ("⤴ arrow pointing rightwards then curving upwards" . "⤴")
    ("🚛 articulated lorry" . "🚛")
    ("🎨 artist palette" . "🎨")
    ("🇦🇼 aruba" . "🇦🇼")
    ("🇦🇨 ascension" . "🇦🇨")
    ("😲 astonished face" . "😲")
    ("👟 athletic shoe" . "👟")
    ("⚛ atom symbol" . "⚛")
    ("🍆 aubergine" . "🍆")
    ("🇦🇺 australia" . "🇦🇺")
    ("🇦🇹 austria" . "🇦🇹")
    ("🏧 automated teller machine" . "🏧")
    ("🚗 automobile" . "🚗")
    ("🥑 avocado" . "🥑")
    ("🇦🇿 azerbaijan" . "🇦🇿")
    ("👶 baby" . "👶")
    ("👶🏻 baby - tone 1" . "👶🏻")
    ("👶🏼 baby - tone 2" . "👶🏼")
    ("👶🏽 baby - tone 3" . "👶🏽")
    ("👶🏾 baby - tone 4" . "👶🏾")
    ("👶🏿 baby - tone 5" . "👶🏿")
    ("👼 baby angel" . "👼")
    ("👼🏻 baby angel - tone 1" . "👼🏻")
    ("👼🏼 baby angel - tone 2" . "👼🏼")
    ("👼🏽 baby angel - tone 3" . "👼🏽")
    ("👼🏾 baby angel - tone 4" . "👼🏾")
    ("👼🏿 baby angel - tone 5" . "👼🏿")
    ("🍼 baby bottle" . "🍼")
    ("🐤 baby chick" . "🐤")
    ("🚼 baby symbol" . "🚼")
    ("🔙 back with leftwards arrow above" . "🔙")
    ("🥓 bacon" . "🥓")
    ("🐫 bactrian camel" . "🐫")
    ("🏸 badminton racquet" . "🏸")
    ("🛄 baggage claim" . "🛄")
    ("🥖 baguette bread" . "🥖")
    ("🇧🇭 bahrain" . "🇧🇭")
    ("🎈 balloon" . "🎈")
    ("🗳 ballot box with ballot" . "🗳")
    ("☑ ballot box with check" . "☑")
    ("🍌 banana" . "🍌")
    ("🇧🇩 bangladesh" . "🇧🇩")
    ("🏦 bank" . "🏦")
    ("💵 banknote with dollar sign" . "💵")
    ("💶 banknote with euro sign" . "💶")
    ("💷 banknote with pound sign" . "💷")
    ("💴 banknote with yen sign" . "💴")
    ("📊 bar chart" . "📊")
    ("🇧🇧 barbados" . "🇧🇧")
    ("💈 barber pole" . "💈")
    ("⚾ baseball" . "⚾")
    ("🏀 basketball and hoop" . "🏀")
    ("🦇 bat" . "🦇")
    ("🛀 bath" . "🛀")
    ("🛀🏻 bath - tone 1" . "🛀🏻")
    ("🛀🏼 bath - tone 2" . "🛀🏼")
    ("🛀🏽 bath - tone 3" . "🛀🏽")
    ("🛀🏾 bath - tone 4" . "🛀🏾")
    ("🛀🏿 bath - tone 5" . "🛀🏿")
    ("🛁 bathtub" . "🛁")
    ("🔋 battery" . "🔋")
    ("🏖 beach with umbrella" . "🏖")
    ("🐻 bear face" . "🐻")
    ("💓 beating heart" . "💓")
    ("🛏 bed" . "🛏")
    ("🍺 beer mug" . "🍺")
    ("🇧🇾 belarus" . "🇧🇾")
    ("🇧🇪 belgium" . "🇧🇪")
    ("🇧🇿 belize" . "🇧🇿")
    ("🔔 bell" . "🔔")
    ("🔕 bell with cancellation stroke" . "🔕")
    ("🛎 bellhop bell" . "🛎")
    ("🇧🇯 benin" . "🇧🇯")
    ("🍱 bento box" . "🍱")
    ("🇧🇲 bermuda" . "🇧🇲")
    ("🇧🇹 bhutan" . "🇧🇹")
    ("🚲 bicycle" . "🚲")
    ("🚴 bicyclist" . "🚴")
    ("🚴🏻 bicyclist - tone 1" . "🚴🏻")
    ("🚴🏼 bicyclist - tone 2" . "🚴🏼")
    ("🚴🏽 bicyclist - tone 3" . "🚴🏽")
    ("🚴🏾 bicyclist - tone 4" . "🚴🏾")
    ("🚴🏿 bicyclist - tone 5" . "🚴🏿")
    ("👙 bikini" . "👙")
    ("🎱 billiards" . "🎱")
    ("☣ biohazard sign" . "☣")
    ("🐦 bird" . "🐦")
    ("🎂 birthday cake" . "🎂")
    ("⏺ black circle for record" . "⏺")
    ("♣ black club suit" . "♣")
    ("♦ black diamond suit" . "♦")
    ("⏬ black down-pointing double triangle" . "⏬")
    ("🖤 black heart" . "🖤")
    ("♥ black heart suit" . "♥")
    ("⬛ black large square" . "⬛")
    ("⏪ black left-pointing double triangle" . "⏪")
    ("⏮ black left-pointing double triangle with vertical bar" . "⏮")
    ("◀ black left-pointing triangle" . "◀")
    ("◾ black medium small square" . "◾")
    ("◼ black medium square" . "◼")
    ("✒ black nib" . "✒")
    ("❓ black question mark ornament" . "❓")
    ("⏩ black right-pointing double triangle" . "⏩")
    ("⏯ black right-pointing double triangle with double vertical bar" . "⏯")
    ("⏭ black right-pointing double triangle with vertical bar" . "⏭")
    ("▶ black right-pointing triangle" . "▶")
    ("➡ black rightwards arrow" . "➡")
    ("✂ black scissors" . "✂")
    ("▪ black small square" . "▪")
    ("♠ black spade suit" . "♠")
    ("🔲 black square button" . "🔲")
    ("⏹ black square for stop" . "⏹")
    ("☀ black sun with rays" . "☀")
    ("☎ black telephone" . "☎")
    ("♻ black universal recycling symbol" . "♻")
    ("⏫ black up-pointing double triangle" . "⏫")
    ("🌼 blossom" . "🌼")
    ("🐡 blowfish" . "🐡")
    ("📘 blue book" . "📘")
    ("💙 blue heart" . "💙")
    ("🐗 boar" . "🐗")
    ("🇧🇴 bolivia" . "🇧🇴")
    ("💣 bomb" . "💣")
    ("🔖 bookmark" . "🔖")
    ("📑 bookmark tabs" . "📑")
    ("📚 books" . "📚")
    ("🇧🇦 bosnia and herzegovina" . "🇧🇦")
    ("🇧🇼 botswana" . "🇧🇼")
    ("🍾 bottle with popping cork" . "🍾")
    ("💐 bouquet" . "💐")
    ("🇧🇻 bouvet island" . "🇧🇻")
    ("🏹 bow and arrow" . "🏹")
    ("🎳 bowling" . "🎳")
    ("🥊 boxing glove" . "🥊")
    ("👦 boy" . "👦")
    ("👦🏻 boy - tone 1" . "👦🏻")
    ("👦🏼 boy - tone 2" . "👦🏼")
    ("👦🏽 boy - tone 3" . "👦🏽")
    ("👦🏾 boy - tone 4" . "👦🏾")
    ("👦🏿 boy - tone 5" . "👦🏿")
    ("🇧🇷 brazil" . "🇧🇷")
    ("🧠 brain" . "🧠")
    ("🍞 bread" . "🍞")
    ("👰 bride with veil" . "👰")
    ("👰🏻 bride with veil - tone 1" . "👰🏻")
    ("👰🏼 bride with veil - tone 2" . "👰🏼")
    ("👰🏽 bride with veil - tone 3" . "👰🏽")
    ("👰🏾 bride with veil - tone 4" . "👰🏾")
    ("👰🏿 bride with veil - tone 5" . "👰🏿")
    ("🌉 bridge at night" . "🌉")
    ("💼 briefcase" . "💼")
    ("🇮🇴 british indian ocean territory" . "🇮🇴")
    ("🇻🇬 british virgin islands" . "🇻🇬")
    ("💔 broken heart" . "💔")
    ("🇧🇳 brunei" . "🇧🇳")
    ("🐛 bug" . "🐛")
    ("🏗 building construction" . "🏗")
    ("🇧🇬 bulgaria" . "🇧🇬")
    ("🇧🇫 burkina faso" . "🇧🇫")
    ("🌯 burrito" . "🌯")
    ("🇧🇮 burundi" . "🇧🇮")
    ("🚌 bus" . "🚌")
    ("🚏 bus stop" . "🚏")
    ("👤 bust in silhouette" . "👤")
    ("👥 busts in silhouette" . "👥")
    ("🦋 butterfly" . "🦋")
    ("🌵 cactus" . "🌵")
    ("📅 calendar" . "📅")
    ("🤙 call me hand" . "🤙")
    ("🤙🏻 call me hand - tone 1" . "🤙🏻")
    ("🤙🏼 call me hand - tone 2" . "🤙🏼")
    ("🤙🏽 call me hand - tone 3" . "🤙🏽")
    ("🤙🏾 call me hand - tone 4" . "🤙🏾")
    ("🤙🏿 call me hand - tone 5" . "🤙🏿")
    ("🇰🇭 cambodia" . "🇰🇭")
    ("📷 camera" . "📷")
    ("📸 camera with flash" . "📸")
    ("🇨🇲 cameroon" . "🇨🇲")
    ("🏕 camping" . "🏕")
    ("🇨🇦 canada" . "🇨🇦")
    ("🇮🇨 canary islands" . "🇮🇨")
    ("♋ cancer" . "♋")
    ("🕯 candle" . "🕯")
    ("🍬 candy" . "🍬")
    ("🛶 canoe" . "🛶")
    ("🇨🇻 cape verde" . "🇨🇻")
    ("♑ capricorn" . "♑")
    ("🗃 card file box" . "🗃")
    ("📇 card index" . "📇")
    ("🗂 card index dividers" . "🗂")
    ("🇧🇶 caribbean netherlands" . "🇧🇶")
    ("🎠 carousel horse" . "🎠")
    ("🎏 carp streamer" . "🎏")
    ("🥕 carrot" . "🥕")
    ("🐈 cat" . "🐈")
    ("🐱 cat face" . "🐱")
    ("😹 cat face with tears of joy" . "😹")
    ("😼 cat face with wry smile" . "😼")
    ("🇰🇾 cayman islands" . "🇰🇾")
    ("🇨🇫 central african republic" . "🇨🇫")
    ("🇪🇦 ceuta, melilla" . "🇪🇦")
    ("🇹🇩 chad" . "🇹🇩")
    ("⛓ chains" . "⛓")
    ("📉 chart with downwards trend" . "📉")
    ("📈 chart with upwards trend" . "📈")
    ("💹 chart with upwards trend and yen sign" . "💹")
    ("📣 cheering megaphone" . "📣")
    ("🧀 cheese wedge" . "🧀")
    ("🏁 chequered flag" . "🏁")
    ("🍒 cherries" . "🍒")
    ("🌸 cherry blossom" . "🌸")
    ("🌰 chestnut" . "🌰")
    ("🐔 chicken" . "🐔")
    ("🚸 children crossing" . "🚸")
    ("🇨🇱 chile" . "🇨🇱")
    ("🇨🇳 china" . "🇨🇳")
    ("🐿 chipmunk" . "🐿")
    ("🍫 chocolate bar" . "🍫")
    ("🇨🇽 christmas island" . "🇨🇽")
    ("🎄 christmas tree" . "🎄")
    ("⛪ church" . "⛪")
    ("🎦 cinema" . "🎦")
    ("🉑 circled ideograph accept" . "🉑")
    ("🉐 circled ideograph advantage" . "🉐")
    ("㊗ circled ideograph congratulation" . "㊗")
    ("㊙ circled ideograph secret" . "㊙")
    ("Ⓜ circled latin capital letter m" . "Ⓜ")
    ("🎪 circus tent" . "🎪")
    ("🏙 cityscape" . "🏙")
    ("🌆 cityscape at dusk" . "🌆")
    ("🎬 clapper board" . "🎬")
    ("👏 clapping hands sign" . "👏")
    ("👏🏻 clapping hands sign - tone 1" . "👏🏻")
    ("👏🏼 clapping hands sign - tone 2" . "👏🏼")
    ("👏🏽 clapping hands sign - tone 3" . "👏🏽")
    ("👏🏾 clapping hands sign - tone 4" . "👏🏾")
    ("👏🏿 clapping hands sign - tone 5" . "👏🏿")
    ("🏛 classical building" . "🏛")
    ("🍻 clinking beer mugs" . "🍻")
    ("🥂 clinking glasses" . "🥂")
    ("📋 clipboard" . "📋")
    ("🇨🇵 clipperton island" . "🇨🇵")
    ("🕗 clock face eight oclock" . "🕗")
    ("🕣 clock face eight-thirty" . "🕣")
    ("🕚 clock face eleven oclock" . "🕚")
    ("🕦 clock face eleven-thirty" . "🕦")
    ("🕔 clock face five oclock" . "🕔")
    ("🕠 clock face five-thirty" . "🕠")
    ("🕓 clock face four oclock" . "🕓")
    ("🕟 clock face four-thirty" . "🕟")
    ("🕘 clock face nine oclock" . "🕘")
    ("🕤 clock face nine-thirty" . "🕤")
    ("🕐 clock face one oclock" . "🕐")
    ("🕜 clock face one-thirty" . "🕜")
    ("🕖 clock face seven oclock" . "🕖")
    ("🕢 clock face seven-thirty" . "🕢")
    ("🕕 clock face six oclock" . "🕕")
    ("🕡 clock face six-thirty" . "🕡")
    ("🕙 clock face ten oclock" . "🕙")
    ("🕥 clock face ten-thirty" . "🕥")
    ("🕒 clock face three oclock" . "🕒")
    ("🕞 clock face three-thirty" . "🕞")
    ("🕛 clock face twelve oclock" . "🕛")
    ("🕧 clock face twelve-thirty" . "🕧")
    ("🕑 clock face two oclock" . "🕑")
    ("🕝 clock face two-thirty" . "🕝")
    ("🔃 clockwise downwards and upwards open circle arrows" . "🔃")
    ("🔁 clockwise rightwards and leftwards open circle arrows" . "🔁")
    ("🔂 clockwise rightwards and leftwards open circle arrows with circled one overlay" . "🔂")
    ("📕 closed book" . "📕")
    ("🔐 closed lock with key" . "🔐")
    ("📪 closed mailbox with lowered flag" . "📪")
    ("📫 closed mailbox with raised flag" . "📫")
    ("🌂 closed umbrella" . "🌂")
    ("☁ cloud" . "☁")
    ("🌩 cloud with lightning" . "🌩")
    ("🌧 cloud with rain" . "🌧")
    ("🌨 cloud with snow" . "🌨")
    ("🌪 cloud with tornado" . "🌪")
    ("🤡 clown face" . "🤡")
    ("🍸 cocktail glass" . "🍸")
    ("🇨🇨 cocos (keeling) islands" . "🇨🇨")
    ("⚰ coffin" . "⚰")
    ("💥 collision symbol" . "💥")
    ("🇨🇴 colombia" . "🇨🇴")
    ("☄ comet" . "☄")
    ("🗜 compression" . "🗜")
    ("🎊 confetti ball" . "🎊")
    ("😖 confounded face" . "😖")
    ("😕 confused face" . "😕")
    ("🚧 construction sign" . "🚧")
    ("👷 construction worker" . "👷")
    ("👷🏻 construction worker - tone 1" . "👷🏻")
    ("👷🏼 construction worker - tone 2" . "👷🏼")
    ("👷🏽 construction worker - tone 3" . "👷🏽")
    ("👷🏾 construction worker - tone 4" . "👷🏾")
    ("👷🏿 construction worker - tone 5" . "👷🏿")
    ("🎛 control knobs" . "🎛")
    ("🏪 convenience store" . "🏪")
    ("🇨🇰 cook islands" . "🇨🇰")
    ("🍚 cooked rice" . "🍚")
    ("🍪 cookie" . "🍪")
    ("🍳 cooking" . "🍳")
    ("© copyright sign" . "©")
    ("🇨🇷 costa rica" . "🇨🇷")
    ("🛋 couch and lamp" . "🛋")
    ("👨❤👨 couple (man,man)" . "👨❤👨")
    ("👩❤👩 couple (woman,woman)" . "👩❤👩")
    ("💑 couple with heart" . "💑")
    ("🐄 cow" . "🐄")
    ("🐮 cow face" . "🐮")
    ("🦀 crab" . "🦀")
    ("💳 credit card" . "💳")
    ("🌙 crescent moon" . "🌙")
    ("🏏 cricket bat and ball" . "🏏")
    ("🇭🇷 croatia" . "🇭🇷")
    ("🐊 crocodile" . "🐊")
    ("🥐 croissant" . "🥐")
    ("❌ cross mark" . "❌")
    ("🎌 crossed flags" . "🎌")
    ("⚔ crossed swords" . "⚔")
    ("👑 crown" . "👑")
    ("😿 crying cat face" . "😿")
    ("😢 crying face" . "😢")
    ("🔮 crystal ball" . "🔮")
    ("🇨🇺 cuba" . "🇨🇺")
    ("🥒 cucumber" . "🥒")
    ("🇨🇼 curaçao" . "🇨🇼")
    ("➰ curly loop" . "➰")
    ("💱 currency exchange" . "💱")
    ("🍛 curry and rice" . "🍛")
    ("🍮 custard" . "🍮")
    ("🛃 customs" . "🛃")
    ("🌀 cyclone" . "🌀")
    ("🇨🇾 cyprus" . "🇨🇾")
    ("🇨🇮 côte d’ivoire" . "🇨🇮")
    ("🗡 dagger knife" . "🗡")
    ("💃 dancer" . "💃")
    ("💃🏻 dancer - tone 1" . "💃🏻")
    ("💃🏼 dancer - tone 2" . "💃🏼")
    ("💃🏽 dancer - tone 3" . "💃🏽")
    ("💃🏾 dancer - tone 4" . "💃🏾")
    ("💃🏿 dancer - tone 5" . "💃🏿")
    ("🍡 dango" . "🍡")
    ("🕶 dark sunglasses" . "🕶")
    ("💨 dash symbol" . "💨")
    ("🌳 deciduous tree" . "🌳")
    ("🦌 deer" . "🦌")
    ("🚚 delivery truck" . "🚚")
    ("🇩🇰 denmark" . "🇩🇰")
    ("🏬 department store" . "🏬")
    ("🏚 derelict house building" . "🏚")
    ("🏜 desert" . "🏜")
    ("🏝 desert island" . "🏝")
    ("🖥 desktop computer" . "🖥")
    ("💠 diamond shape with a dot inside" . "💠")
    ("🇩🇬 diego garcia" . "🇩🇬")
    ("🎯 direct hit" . "🎯")
    ("😥 disappointed but relieved face" . "😥")
    ("😞 disappointed face" . "😞")
    ("😵 dizzy face" . "😵")
    ("💫 dizzy symbol" . "💫")
    ("🇩🇯 djibouti" . "🇩🇯")
    ("🚯 do not litter symbol" . "🚯")
    ("🐕 dog" . "🐕")
    ("🐶 dog face" . "🐶")
    ("🐬 dolphin" . "🐬")
    ("🇩🇲 dominica" . "🇩🇲")
    ("🚪 door" . "🚪")
    ("➿ double curly loop" . "➿")
    ("‼ double exclamation mark" . "‼")
    ("⏸ double vertical bar" . "⏸")
    ("🍩 doughnut" . "🍩")
    ("🕊 dove of peace" . "🕊")
    ("🔻 down-pointing red triangle" . "🔻")
    ("🔽 down-pointing small red triangle" . "🔽")
    ("⬇ downwards black arrow" . "⬇")
    ("🐉 dragon" . "🐉")
    ("🐲 dragon face" . "🐲")
    ("👗 dress" . "👗")
    ("🐪 dromedary camel" . "🐪")
    ("🤤 drooling face" . "🤤")
    ("💧 droplet" . "💧")
    ("🥁 drum with drumsticks" . "🥁")
    ("🦆 duck" . "🦆")
    ("📀 dvd" . "📀")
    ("📧 e-mail symbol" . "📧")
    ("🦅 eagle" . "🦅")
    ("👂 ear" . "👂")
    ("👂🏻 ear - tone 1" . "👂🏻")
    ("👂🏼 ear - tone 2" . "👂🏼")
    ("👂🏽 ear - tone 3" . "👂🏽")
    ("👂🏾 ear - tone 4" . "👂🏾")
    ("👂🏿 ear - tone 5" . "👂🏿")
    ("🌽 ear of maize" . "🌽")
    ("🌾 ear of rice" . "🌾")
    ("🌎 earth globe americas" . "🌎")
    ("🌏 earth globe asia-australia" . "🌏")
    ("🌍 earth globe europe-africa" . "🌍")
    ("🇪🇨 ecuador" . "🇪🇨")
    ("🥚 egg" . "🥚")
    ("🇪🇬 egypt" . "🇪🇬")
    ("✴ eight pointed black star" . "✴")
    ("✳ eight spoked asterisk" . "✳")
    ("⏏ eject symbol" . "⏏")
    ("🇸🇻 el salvador" . "🇸🇻")
    ("💡 electric light bulb" . "💡")
    ("🔌 electric plug" . "🔌")
    ("🔦 electric torch" . "🔦")
    ("🐘 elephant" . "🐘")
    ("🏻 emoji modifier fitzpatrick type-1-2" . "🏻")
    ("🏼 emoji modifier fitzpatrick type-3" . "🏼")
    ("🏽 emoji modifier fitzpatrick type-4" . "🏽")
    ("🏾 emoji modifier fitzpatrick type-5" . "🏾")
    ("🏿 emoji modifier fitzpatrick type-6" . "🏿")
    ("🔚 end with leftwards arrow above" . "🔚")
    ("✉ envelope" . "✉")
    ("📩 envelope with downwards arrow above" . "📩")
    ("🇬🇶 equatorial guinea" . "🇬🇶")
    ("🇪🇷 eritrea" . "🇪🇷")
    ("🇪🇪 estonia" . "🇪🇪")
    ("🇪🇹 ethiopia" . "🇪🇹")
    ("🏰 european castle" . "🏰")
    ("🏤 european post office" . "🏤")
    ("🇪🇺 european union" . "🇪🇺")
    ("🌲 evergreen tree" . "🌲")
    ("⁉ exclamation question mark" . "⁉")
    ("😑 expressionless face" . "😑")
    ("👽 extraterrestrial alien" . "👽")
    ("👁 eye" . "👁")
    ("👁🗨 eye in speech bubble" . "👁🗨")
    ("👓 eyeglasses" . "👓")
    ("👀 eyes" . "👀")
    ("💆 face massage" . "💆")
    ("💆🏻 face massage - tone 1" . "💆🏻")
    ("💆🏼 face massage - tone 2" . "💆🏼")
    ("💆🏽 face massage - tone 3" . "💆🏽")
    ("💆🏾 face massage - tone 4" . "💆🏾")
    ("💆🏿 face massage - tone 5" . "💆🏿")
    ("🤦 face palm" . "🤦")
    ("🤦🏻 face palm - tone 1" . "🤦🏻")
    ("🤦🏼 face palm - tone 2" . "🤦🏼")
    ("🤦🏽 face palm - tone 3" . "🤦🏽")
    ("🤦🏾 face palm - tone 4" . "🤦🏾")
    ("🤦🏿 face palm - tone 5" . "🤦🏿")
    ("😋 face savouring delicious food" . "😋")
    ("😱 face screaming in fear" . "😱")
    ("😘 face throwing a kiss" . "😘")
    ("😓 face with cold sweat" . "😓")
    ("🤠 face with cowboy hat" . "🤠")
    ("🤕 face with head-bandage" . "🤕")
    ("😤 face with look of triumph" . "😤")
    ("😷 face with medical mask" . "😷")
    ("🙅 face with no good gesture" . "🙅")
    ("🙅🏻 face with no good gesture - tone 1" . "🙅🏻")
    ("🙅🏼 face with no good gesture - tone 2" . "🙅🏼")
    ("🙅🏽 face with no good gesture - tone 3" . "🙅🏽")
    ("🙅🏾 face with no good gesture - tone 4" . "🙅🏾")
    ("🙅🏿 face with no good gesture - tone 5" . "🙅🏿")
    ("🙆 face with ok gesture" . "🙆")
    ("🙆🏻 face with ok gesture tone1" . "🙆🏻")
    ("🙆🏼 face with ok gesture tone2" . "🙆🏼")
    ("🙆🏽 face with ok gesture tone3" . "🙆🏽")
    ("🙆🏾 face with ok gesture tone4" . "🙆🏾")
    ("🙆🏿 face with ok gesture tone5" . "🙆🏿")
    ("😮 face with open mouth" . "😮")
    ("😰 face with open mouth and cold sweat" . "😰")
    ("🙄 face with rolling eyes" . "🙄")
    ("😛 face with stuck-out tongue" . "😛")
    ("😝 face with stuck-out tongue and tightly-closed eyes" . "😝")
    ("😜 face with stuck-out tongue and winking eye" . "😜")
    ("😂 face with tears of joy" . "😂")
    ("🤒 face with thermometer" . "🤒")
    ("😶 face without mouth" . "😶")
    ("🏭 factory" . "🏭")
    ("🇫🇰 falkland islands" . "🇫🇰")
    ("🍂 fallen leaf" . "🍂")
    ("👪 family" . "👪")
    ("👨👨👦 family (man,man,boy)" . "👨👨👦")
    ("👨👨👦👦 family (man,man,boy,boy)" . "👨👨👦👦")
    ("👨👨👧 family (man,man,girl)" . "👨👨👧")
    ("👨👨👧👦 family (man,man,girl,boy)" . "👨👨👧👦")
    ("👨👨👧👧 family (man,man,girl,girl)" . "👨👨👧👧")
    ("👨👩👦👦 family (man,woman,boy,boy)" . "👨👩👦👦")
    ("👨👩👧 family (man,woman,girl)" . "👨👩👧")
    ("👨👩👧👦 family (man,woman,girl,boy)" . "👨👩👧👦")
    ("👨👩👧👧 family (man,woman,girl,girl)" . "👨👩👧👧")
    ("👩👩👦 family (woman,woman,boy)" . "👩👩👦")
    ("👩👩👦👦 family (woman,woman,boy,boy)" . "👩👩👦👦")
    ("👩👩👧 family (woman,woman,girl)" . "👩👩👧")
    ("👩👩👧👦 family (woman,woman,girl,boy)" . "👩👩👧👦")
    ("👩👩👧👧 family (woman,woman,girl,girl)" . "👩👩👧👧")
    ("🇫🇴 faroe islands" . "🇫🇴")
    ("🎅 father christmas" . "🎅")
    ("🎅🏻 father christmas - tone 1" . "🎅🏻")
    ("🎅🏼 father christmas - tone 2" . "🎅🏼")
    ("🎅🏽 father christmas - tone 3" . "🎅🏽")
    ("🎅🏾 father christmas - tone 4" . "🎅🏾")
    ("🎅🏿 father christmas - tone 5" . "🎅🏿")
    ("📠 fax machine" . "📠")
    ("😨 fearful face" . "😨")
    ("🤺 fencer" . "🤺")
    ("🎡 ferris wheel" . "🎡")
    ("⛴ ferry" . "⛴")
    ("🏑 field hockey stick and ball" . "🏑")
    ("🇫🇯 fiji" . "🇫🇯")
    ("🗄 file cabinet" . "🗄")
    ("📁 file folder" . "📁")
    ("🎞 film frames" . "🎞")
    ("📽 film projector" . "📽")
    ("🇫🇮 finland" . "🇫🇮")
    ("🔥 fire" . "🔥")
    ("🚒 fire engine" . "🚒")
    ("🎇 firework sparkler" . "🎇")
    ("🎆 fireworks" . "🎆")
    ("🥇 first place medal" . "🥇")
    ("🌓 first quarter moon symbol" . "🌓")
    ("🌛 first quarter moon with face" . "🌛")
    ("🐟 fish" . "🐟")
    ("🍥 fish cake with swirl design" . "🍥")
    ("🎣 fishing pole and fish" . "🎣")
    ("👊 fisted hand sign" . "👊")
    ("👊🏻 fisted hand sign - tone 1" . "👊🏻")
    ("👊🏼 fisted hand sign - tone 2" . "👊🏼")
    ("👊🏽 fisted hand sign - tone 3" . "👊🏽")
    ("👊🏾 fisted hand sign - tone 4" . "👊🏾")
    ("👊🏿 fisted hand sign - tone 5" . "👊🏿")
    ("⛳ flag in hole" . "⛳")
    ("⚜ fleur-de-lis" . "⚜")
    ("💪 flexed biceps" . "💪")
    ("💪🏻 flexed biceps - tone 1" . "💪🏻")
    ("💪🏼 flexed biceps - tone 2" . "💪🏼")
    ("💪🏽 flexed biceps - tone 3" . "💪🏽")
    ("💪🏾 flexed biceps - tone 4" . "💪🏾")
    ("💪🏿 flexed biceps - tone 5" . "💪🏿")
    ("💾 floppy disk" . "💾")
    ("🎴 flower playing cards" . "🎴")
    ("😳 flushed face" . "😳")
    ("🌫 fog" . "🌫")
    ("🌁 foggy" . "🌁")
    ("👣 footprints" . "👣")
    ("🍴 fork and knife" . "🍴")
    ("🍽 fork and knife with plate" . "🍽")
    ("⛲ fountain" . "⛲")
    ("🍀 four leaf clover" . "🍀")
    ("🦊 fox face" . "🦊")
    ("🖼 frame with picture" . "🖼")
    ("🇫🇷 france" . "🇫🇷")
    ("🍟 french fries" . "🍟")
    ("🇬🇫 french guiana" . "🇬🇫")
    ("🇵🇫 french polynesia" . "🇵🇫")
    ("🇹🇫 french southern territories" . "🇹🇫")
    ("🍤 fried shrimp" . "🍤")
    ("🐸 frog face" . "🐸")
    ("🐥 front-facing baby chick" . "🐥")
    ("😦 frowning face with open mouth" . "😦")
    ("⛽ fuel pump" . "⛽")
    ("🌕 full moon symbol" . "🌕")
    ("🌝 full moon with face" . "🌝")
    ("⚱ funeral urn" . "⚱")
    ("🇬🇦 gabon" . "🇬🇦")
    ("🎲 game die" . "🎲")
    ("🏳🌈 gay_pride_flag" . "🏳🌈")
    ("⚙ gear" . "⚙")
    ("💎 gem stone" . "💎")
    ("♊ gemini" . "♊")
    ("🇬🇪 georgia" . "🇬🇪")
    ("🇩🇪 germany" . "🇩🇪")
    ("🇬🇭 ghana" . "🇬🇭")
    ("👻 ghost" . "👻")
    ("🇬🇮 gibraltar" . "🇬🇮")
    ("👧 girl" . "👧")
    ("👧🏻 girl - tone 1" . "👧🏻")
    ("👧🏼 girl - tone 2" . "👧🏼")
    ("👧🏽 girl - tone 3" . "👧🏽")
    ("👧🏾 girl - tone 4" . "👧🏾")
    ("👧🏿 girl - tone 5" . "👧🏿")
    ("🥛 glass of milk" . "🥛")
    ("🌐 globe with meridians" . "🌐")
    ("🌟 glowing star" . "🌟")
    ("🥅 goal net" . "🥅")
    ("🐐 goat" . "🐐")
    ("🏌 golfer" . "🏌")
    ("🦍 gorilla" . "🦍")
    ("🎓 graduation cap" . "🎓")
    ("🍇 grapes" . "🍇")
    ("🇬🇧 great britain" . "🇬🇧")
    ("🇬🇷 greece" . "🇬🇷")
    ("🍏 green apple" . "🍏")
    ("📗 green book" . "📗")
    ("💚 green heart" . "💚")
    ("🥗 green salad" . "🥗")
    ("🇬🇱 greenland" . "🇬🇱")
    ("🇬🇩 grenada" . "🇬🇩")
    ("😬 grimacing face" . "😬")
    ("😸 grinning cat face with smiling eyes" . "😸")
    ("😀 grinning face" . "😀")
    ("😁 grinning face with smiling eyes" . "😁")
    ("💗 growing heart" . "💗")
    ("🇬🇵 guadeloupe" . "🇬🇵")
    ("🇬🇺 guam" . "🇬🇺")
    ("💂 guardsman" . "💂")
    ("💂🏻 guardsman - tone 1" . "💂🏻")
    ("💂🏼 guardsman - tone 2" . "💂🏼")
    ("💂🏽 guardsman - tone 3" . "💂🏽")
    ("💂🏾 guardsman - tone 4" . "💂🏾")
    ("💂🏿 guardsman - tone 5" . "💂🏿")
    ("🇬🇹 guatemala" . "🇬🇹")
    ("🇬🇬 guernsey" . "🇬🇬")
    ("🇬🇳 guinea" . "🇬🇳")
    ("🇬🇼 guinea-bissau" . "🇬🇼")
    ("🎸 guitar" . "🎸")
    ("🇬🇾 guyana" . "🇬🇾")
    ("💇 haircut" . "💇")
    ("💇🏻 haircut - tone 1" . "💇🏻")
    ("💇🏼 haircut - tone 2" . "💇🏼")
    ("💇🏽 haircut - tone 3" . "💇🏽")
    ("💇🏾 haircut - tone 4" . "💇🏾")
    ("💇🏿 haircut - tone 5" . "💇🏿")
    ("🇭🇹 haiti" . "🇭🇹")
    ("🍔 hamburger" . "🍔")
    ("🔨 hammer" . "🔨")
    ("⚒ hammer and pick" . "⚒")
    ("🛠 hammer and wrench" . "🛠")
    ("🐹 hamster face" . "🐹")
    ("🤞 hand with first and index finger crossed" . "🤞")
    ("🤞🏻 hand with index and middle fingers crossed - tone 1" . "🤞🏻")
    ("🤞🏼 hand with index and middle fingers crossed - tone 2" . "🤞🏼")
    ("🤞🏽 hand with index and middle fingers crossed - tone 3" . "🤞🏽")
    ("🤞🏾 hand with index and middle fingers crossed - tone 4" . "🤞🏾")
    ("🤞🏿 hand with index and middle fingers crossed - tone 5" . "🤞🏿")
    ("👜 handbag" . "👜")
    ("🤾 handball" . "🤾")
    ("🤾🏻 handball - tone 1" . "🤾🏻")
    ("🤾🏼 handball - tone 2" . "🤾🏼")
    ("🤾🏽 handball - tone 3" . "🤾🏽")
    ("🤾🏾 handball - tone 4" . "🤾🏾")
    ("🤾🏿 handball - tone 5" . "🤾🏿")
    ("🤝 handshake" . "🤝")
    ("🤝🏻 handshake - tone 1" . "🤝🏻")
    ("🤝🏼 handshake - tone 2" . "🤝🏼")
    ("🤝🏽 handshake - tone 3" . "🤝🏽")
    ("🤝🏾 handshake - tone 4" . "🤝🏾")
    ("🤝🏿 handshake - tone 5" . "🤝🏿")
    ("🙋 happy person raising one hand" . "🙋")
    ("🙋🏻 happy person raising one hand tone1" . "🙋🏻")
    ("🙋🏼 happy person raising one hand tone2" . "🙋🏼")
    ("🙋🏽 happy person raising one hand tone3" . "🙋🏽")
    ("🙋🏾 happy person raising one hand tone4" . "🙋🏾")
    ("🙋🏿 happy person raising one hand tone5" . "🙋🏿")
    ("🐣 hatching chick" . "🐣")
    ("🎧 headphone" . "🎧")
    ("🙉 hear-no-evil monkey" . "🙉")
    ("🇭🇲 heard island and mcdonald islands" . "🇭🇲")
    ("💟 heart decoration" . "💟")
    ("💘 heart with arrow" . "💘")
    ("💝 heart with ribbon" . "💝")
    ("❤ heavy black heart" . "❤")
    ("✔ heavy check mark" . "✔")
    ("➗ heavy division sign" . "➗")
    ("💲 heavy dollar sign" . "💲")
    ("❗ heavy exclamation mark symbol" . "❗")
    ("❣ heavy heart exclamation mark ornament" . "❣")
    ("⭕ heavy large circle" . "⭕")
    ("➖ heavy minus sign" . "➖")
    ("✖ heavy multiplication x" . "✖")
    ("➕ heavy plus sign" . "➕")
    ("🚁 helicopter" . "🚁")
    ("⛑ helmet with white cross" . "⛑")
    ("🌿 herb" . "🌿")
    ("🌺 hibiscus" . "🌺")
    ("🔆 high brightness symbol" . "🔆")
    ("⚡ high voltage sign" . "⚡")
    ("👠 high-heeled shoe" . "👠")
    ("🚄 high-speed train" . "🚄")
    ("🚅 high-speed train with bullet nose" . "🚅")
    ("🔪 hocho" . "🔪")
    ("🕳 hole" . "🕳")
    ("🇭🇳 honduras" . "🇭🇳")
    ("🍯 honey pot" . "🍯")
    ("🐝 honeybee" . "🐝")
    ("🇭🇰 hong kong" . "🇭🇰")
    ("🚥 horizontal traffic light" . "🚥")
    ("🐎 horse" . "🐎")
    ("🐴 horse face" . "🐴")
    ("🏇 horse racing" . "🏇")
    ("🏇🏻 horse racing - tone 1" . "🏇🏻")
    ("🏇🏼 horse racing - tone 2" . "🏇🏼")
    ("🏇🏽 horse racing - tone 3" . "🏇🏽")
    ("🏇🏾 horse racing - tone 4" . "🏇🏾")
    ("🏇🏿 horse racing - tone 5" . "🏇🏿")
    ("🏥 hospital" . "🏥")
    ("☕ hot beverage" . "☕")
    ("🌭 hot dog" . "🌭")
    ("🌶 hot pepper" . "🌶")
    ("♨ hot springs" . "♨")
    ("🏨 hotel" . "🏨")
    ("⌛ hourglass" . "⌛")
    ("⏳ hourglass with flowing sand" . "⏳")
    ("🏠 house building" . "🏠")
    ("🏘 house buildings" . "🏘")
    ("🏡 house with garden" . "🏡")
    ("🤗 hugging face" . "🤗")
    ("💯 hundred points symbol" . "💯")
    ("🇭🇺 hungary" . "🇭🇺")
    ("😯 hushed face" . "😯")
    ("🍨 ice cream" . "🍨")
    ("🏒 ice hockey stick and puck" . "🏒")
    ("⛸ ice skate" . "⛸")
    ("🇮🇸 iceland" . "🇮🇸")
    ("👿 imp" . "👿")
    ("📥 inbox tray" . "📥")
    ("📨 incoming envelope" . "📨")
    ("🇮🇳 india" . "🇮🇳")
    ("🇮🇩 indonesia" . "🇮🇩")
    ("💁 information desk person" . "💁")
    ("💁🏻 information desk person - tone 1" . "💁🏻")
    ("💁🏼 information desk person - tone 2" . "💁🏼")
    ("💁🏽 information desk person - tone 3" . "💁🏽")
    ("💁🏾 information desk person - tone 4" . "💁🏾")
    ("💁🏿 information desk person - tone 5" . "💁🏿")
    ("ℹ information source" . "ℹ")
    ("🔠 input symbol for latin capital letters" . "🔠")
    ("🔤 input symbol for latin letters" . "🔤")
    ("🔡 input symbol for latin small letters" . "🔡")
    ("🔢 input symbol for numbers" . "🔢")
    ("🔣 input symbol for symbols" . "🔣")
    ("🇮🇷 iran" . "🇮🇷")
    ("🇮🇶 iraq" . "🇮🇶")
    ("🇮🇪 ireland" . "🇮🇪")
    ("🇮🇲 isle of man" . "🇮🇲")
    ("🇮🇱 israel" . "🇮🇱")
    ("🇮🇹 italy" . "🇮🇹")
    ("🏮 izakaya lantern" . "🏮")
    ("🎃 jack-o-lantern" . "🎃")
    ("🇯🇲 jamaica" . "🇯🇲")
    ("🇯🇵 japan" . "🇯🇵")
    ("🏯 japanese castle" . "🏯")
    ("🎎 japanese dolls" . "🎎")
    ("👺 japanese goblin" . "👺")
    ("👹 japanese ogre" . "👹")
    ("🏣 japanese post office" . "🏣")
    ("🔰 japanese symbol for beginner" . "🔰")
    ("👖 jeans" . "👖")
    ("🇯🇪 jersey" . "🇯🇪")
    ("🇯🇴 jordan" . "🇯🇴")
    ("🕹 joystick" . "🕹")
    ("🤹 juggling" . "🤹")
    ("🤹🏻 juggling - tone 1" . "🤹🏻")
    ("🤹🏼 juggling - tone 2" . "🤹🏼")
    ("🤹🏽 juggling - tone 3" . "🤹🏽")
    ("🤹🏾 juggling - tone 4" . "🤹🏾")
    ("🤹🏿 juggling - tone 5" . "🤹🏿")
    ("🕋 kaaba" . "🕋")
    ("🇰🇿 kazakhstan" . "🇰🇿")
    ("🇰🇪 kenya" . "🇰🇪")
    ("🔑 key" . "🔑")
    ("⌨ keyboard" . "⌨")
    ("*⃣ keycap asterisk" . "*⃣")
    ("8⃣ keycap digit eight" . "8⃣")
    ("5⃣ keycap digit five" . "5⃣")
    ("4⃣ keycap digit four" . "4⃣")
    ("9⃣ keycap digit nine" . "9⃣")
    ("1⃣ keycap digit one" . "1⃣")
    ("7⃣ keycap digit seven" . "7⃣")
    ("6⃣ keycap digit six" . "6⃣")
    ("3⃣ keycap digit three" . "3⃣")
    ("2⃣ keycap digit two" . "2⃣")
    ("0⃣ keycap digit zero" . "0⃣")
    ("#⃣ keycap number sign" . "#⃣")
    ("🔟 keycap ten" . "🔟")
    ("👘 kimono" . "👘")
    ("🇰🇮 kiribati" . "🇰🇮")
    ("💏 kiss" . "💏")
    ("👨❤💋👨 kiss (man,man)" . "👨❤💋👨")
    ("👩❤💋👩 kiss (woman,woman)" . "👩❤💋👩")
    ("💋 kiss mark" . "💋")
    ("😽 kissing cat face with closed eyes" . "😽")
    ("😗 kissing face" . "😗")
    ("😚 kissing face with closed eyes" . "😚")
    ("😙 kissing face with smiling eyes" . "😙")
    ("🥝 kiwifruit" . "🥝")
    ("🐨 koala" . "🐨")
    ("🇰🇷 korea" . "🇰🇷")
    ("🇽🇰 kosovo" . "🇽🇰")
    ("🇰🇼 kuwait" . "🇰🇼")
    ("🇰🇬 kyrgyzstan" . "🇰🇬")
    ("🏷 label" . "🏷")
    ("🐞 lady beetle" . "🐞")
    ("🇱🇦 laos" . "🇱🇦")
    ("🔵 large blue circle" . "🔵")
    ("🔷 large blue diamond" . "🔷")
    ("🔶 large orange diamond" . "🔶")
    ("🔴 large red circle" . "🔴")
    ("🌗 last quarter moon symbol" . "🌗")
    ("🌜 last quarter moon with face" . "🌜")
    ("✝ latin cross" . "✝")
    ("🇱🇻 latvia" . "🇱🇻")
    ("🍃 leaf fluttering in wind" . "🍃")
    ("🇱🇧 lebanon" . "🇱🇧")
    ("📒 ledger" . "📒")
    ("🤛🏻 left facing fist - tone 1" . "🤛🏻")
    ("🤛🏼 left facing fist - tone 2" . "🤛🏼")
    ("🤛🏽 left facing fist - tone 3" . "🤛🏽")
    ("🤛🏾 left facing fist - tone 4" . "🤛🏾")
    ("🤛🏿 left facing fist - tone 5" . "🤛🏿")
    ("🛅 left luggage" . "🛅")
    ("↔ left right arrow" . "↔")
    ("🗨 left speech bubble" . "🗨")
    ("🤛 left-facing fist" . "🤛")
    ("🔍 left-pointing magnifying glass" . "🔍")
    ("↩ leftwards arrow with hook" . "↩")
    ("⬅ leftwards black arrow" . "⬅")
    ("🍋 lemon" . "🍋")
    ("♌ leo" . "♌")
    ("🐆 leopard" . "🐆")
    ("🇱🇸 lesotho" . "🇱🇸")
    ("🎚 level slider" . "🎚")
    ("🇱🇷 liberia" . "🇱🇷")
    ("♎ libra" . "♎")
    ("🇱🇾 libya" . "🇱🇾")
    ("🇱🇮 liechtenstein" . "🇱🇮")
    ("🚈 light rail" . "🚈")
    ("🔗 link symbol" . "🔗")
    ("🖇 linked paperclips" . "🖇")
    ("🦁 lion face" . "🦁")
    ("💄 lipstick" . "💄")
    ("🇱🇹 lithuania" . "🇱🇹")
    ("🦎 lizard" . "🦎")
    ("🔒 lock" . "🔒")
    ("🔏 lock with ink pen" . "🔏")
    ("🍭 lollipop" . "🍭")
    ("😭 loudly crying face" . "😭")
    ("🏩 love hotel" . "🏩")
    ("💌 love letter" . "💌")
    ("🔅 low brightness symbol" . "🔅")
    ("🖊 lower left ballpoint pen" . "🖊")
    ("🖍 lower left crayon" . "🖍")
    ("🖋 lower left fountain pen" . "🖋")
    ("🖌 lower left paintbrush" . "🖌")
    ("🇱🇺 luxembourg" . "🇱🇺")
    ("🤥 lying face" . "🤥")
    ("🇲🇴 macau" . "🇲🇴")
    ("🇲🇰 macedonia" . "🇲🇰")
    ("🇲🇬 madagascar" . "🇲🇬")
    ("🀄 mahjong tile red dragon" . "🀄")
    ("🇲🇼 malawi" . "🇲🇼")
    ("🇲🇾 malaysia" . "🇲🇾")
    ("🇲🇻 maldives" . "🇲🇻")
    ("🇲🇱 mali" . "🇲🇱")
    ("🇲🇹 malta" . "🇲🇹")
    ("👨 man" . "👨")
    ("👨🏻 man - tone 1" . "👨🏻")
    ("👨🏼 man - tone 2" . "👨🏼")
    ("👨🏽 man - tone 3" . "👨🏽")
    ("👨🏾 man - tone 4" . "👨🏾")
    ("👨🏿 man - tone 5" . "👨🏿")
    ("👫 man and woman holding hands" . "👫")
    ("🕺 man dancing" . "🕺")
    ("🕺🏻 man dancing - tone 1" . "🕺🏻")
    ("🕺🏼 man dancing - tone 2" . "🕺🏼")
    ("🕺🏽 man dancing - tone 3" . "🕺🏽")
    ("🕺🏾 man dancing - tone 4" . "🕺🏾")
    ("🕺🏿 man dancing - tone 5" . "🕺🏿")
    ("🕴 man in business suit levitating" . "🕴")
    ("🤵 man in tuxedo" . "🤵")
    ("🤵🏻 man in tuxedo - tone 1" . "🤵🏻")
    ("🤵🏼 man in tuxedo - tone 2" . "🤵🏼")
    ("🤵🏽 man in tuxedo - tone 3" . "🤵🏽")
    ("🤵🏾 man in tuxedo - tone 4" . "🤵🏾")
    ("🤵🏿 man in tuxedo - tone 5" . "🤵🏿")
    ("👲 man with gua pi mao" . "👲")
    ("👲🏻 man with gua pi mao - tone 1" . "👲🏻")
    ("👲🏼 man with gua pi mao - tone 2" . "👲🏼")
    ("👲🏽 man with gua pi mao - tone 3" . "👲🏽")
    ("👲🏾 man with gua pi mao - tone 4" . "👲🏾")
    ("👲🏿 man with gua pi mao - tone 5" . "👲🏿")
    ("👳 man with turban" . "👳")
    ("👳🏻 man with turban - tone 1" . "👳🏻")
    ("👳🏼 man with turban - tone 2" . "👳🏼")
    ("👳🏽 man with turban - tone 3" . "👳🏽")
    ("👳🏾 man with turban - tone 4" . "👳🏾")
    ("👳🏿 man with turban - tone 5" . "👳🏿")
    ("👞 mans shoe" . "👞")
    ("🕰 mantlepiece clock" . "🕰")
    ("🍁 maple leaf" . "🍁")
    ("🥋 martial arts uniform" . "🥋")
    ("🇲🇶 martinique" . "🇲🇶")
    ("🇲🇷 mauritania" . "🇲🇷")
    ("🇲🇺 mauritius" . "🇲🇺")
    ("🇾🇹 mayotte" . "🇾🇹")
    ("🍖 meat on bone" . "🍖")
    ("⚫ medium black circle" . "⚫")
    ("⚪ medium white circle" . "⚪")
    ("🍈 melon" . "🍈")
    ("📝 memo" . "📝")
    ("🕎 menorah with nine branches" . "🕎")
    ("🚹 mens symbol" . "🚹")
    ("🚇 metro" . "🚇")
    ("🇲🇽 mexico" . "🇲🇽")
    ("🇫🇲 micronesia" . "🇫🇲")
    ("🎤 microphone" . "🎤")
    ("🔬 microscope" . "🔬")
    ("🎖 military medal" . "🎖")
    ("🌌 milky way" . "🌌")
    ("🚐 minibus" . "🚐")
    ("💽 minidisc" . "💽")
    ("📱 mobile phone" . "📱")
    ("📴 mobile phone off" . "📴")
    ("📲 mobile phone with rightwards arrow at left" . "📲")
    ("🇲🇩 moldova" . "🇲🇩")
    ("🇲🇨 monaco" . "🇲🇨")
    ("💰 money bag" . "💰")
    ("💸 money with wings" . "💸")
    ("🤑 money-mouth face" . "🤑")
    ("🇲🇳 mongolia" . "🇲🇳")
    ("🐒 monkey" . "🐒")
    ("🐵 monkey face" . "🐵")
    ("🚝 monorail" . "🚝")
    ("🇲🇪 montenegro" . "🇲🇪")
    ("🇲🇸 montserrat" . "🇲🇸")
    ("🎑 moon viewing ceremony" . "🎑")
    ("🇲🇦 morocco" . "🇲🇦")
    ("🕌 mosque" . "🕌")
    ("🤶 mother christmas" . "🤶")
    ("🤶🏻 mother christmas - tone 1" . "🤶🏻")
    ("🤶🏼 mother christmas - tone 2" . "🤶🏼")
    ("🤶🏽 mother christmas - tone 3" . "🤶🏽")
    ("🤶🏾 mother christmas - tone 4" . "🤶🏾")
    ("🤶🏿 mother christmas - tone 5" . "🤶🏿")
    ("🛵 motor scooter" . "🛵")
    ("🛥 motorboat" . "🛥")
    ("🛣 motorway" . "🛣")
    ("🗻 mount fuji" . "🗻")
    ("⛰ mountain" . "⛰")
    ("🚵 mountain bicyclist" . "🚵")
    ("🚵🏻 mountain bicyclist - tone 1" . "🚵🏻")
    ("🚵🏼 mountain bicyclist - tone 2" . "🚵🏼")
    ("🚵🏽 mountain bicyclist - tone 3" . "🚵🏽")
    ("🚵🏾 mountain bicyclist - tone 4" . "🚵🏾")
    ("🚵🏿 mountain bicyclist - tone 5" . "🚵🏿")
    ("🚠 mountain cableway" . "🚠")
    ("🚞 mountain railway" . "🚞")
    ("🐁 mouse" . "🐁")
    ("🐭 mouse face" . "🐭")
    ("👄 mouth" . "👄")
    ("🎥 movie camera" . "🎥")
    ("🗿 moyai" . "🗿")
    ("🇲🇿 mozambique" . "🇲🇿")
    ("🎶 multiple musical notes" . "🎶")
    ("🍄 mushroom" . "🍄")
    ("🎹 musical keyboard" . "🎹")
    ("🎵 musical note" . "🎵")
    ("🎼 musical score" . "🎼")
    ("🇲🇲 myanmar" . "🇲🇲")
    ("💅 nail polish" . "💅")
    ("💅🏻 nail polish - tone 1" . "💅🏻")
    ("💅🏼 nail polish - tone 2" . "💅🏼")
    ("💅🏽 nail polish - tone 3" . "💅🏽")
    ("💅🏾 nail polish - tone 4" . "💅🏾")
    ("💅🏿 nail polish - tone 5" . "💅🏿")
    ("📛 name badge" . "📛")
    ("🇳🇦 namibia" . "🇳🇦")
    ("🏞 national park" . "🏞")
    ("🇳🇷 nauru" . "🇳🇷")
    ("🤢 nauseated face" . "🤢")
    ("👔 necktie" . "👔")
    ("🆎 negative squared ab" . "🆎")
    ("❎ negative squared cross mark" . "❎")
    ("🅰 negative squared latin capital letter a" . "🅰")
    ("🅱 negative squared latin capital letter b" . "🅱")
    ("🅾 negative squared latin capital letter o" . "🅾")
    ("🅿 negative squared latin capital letter p" . "🅿")
    ("🇳🇵 nepal" . "🇳🇵")
    ("🤓 nerd face" . "🤓")
    ("😐 neutral face" . "😐")
    ("🇳🇨 new caledonia" . "🇳🇨")
    ("🌑 new moon symbol" . "🌑")
    ("🌚 new moon with face" . "🌚")
    ("🇳🇿 new zealand" . "🇳🇿")
    ("📰 newspaper" . "📰")
    ("🇳🇮 nicaragua" . "🇳🇮")
    ("🇳🇪 niger" . "🇳🇪")
    ("🇳🇬 nigeria" . "🇳🇬")
    ("🌃 night with stars" . "🌃")
    ("🇳🇺 niue" . "🇳🇺")
    ("🚳 no bicycles" . "🚳")
    ("⛔ no entry" . "⛔")
    ("🚫 no entry sign" . "🚫")
    ("📵 no mobile phones" . "📵")
    ("🔞 no one under eighteen symbol" . "🔞")
    ("🚷 no pedestrians" . "🚷")
    ("🚭 no smoking symbol" . "🚭")
    ("🚱 non-potable water symbol" . "🚱")
    ("🇳🇫 norfolk island" . "🇳🇫")
    ("↗ north east arrow" . "↗")
    ("🇰🇵 north korea" . "🇰🇵")
    ("↖ north west arrow" . "↖")
    ("🇲🇵 northern mariana islands" . "🇲🇵")
    ("🇳🇴 norway" . "🇳🇴")
    ("👃 nose" . "👃")
    ("👃🏻 nose - tone 1" . "👃🏻")
    ("👃🏼 nose - tone 2" . "👃🏼")
    ("👃🏽 nose - tone 3" . "👃🏽")
    ("👃🏾 nose - tone 4" . "👃🏾")
    ("👃🏿 nose - tone 5" . "👃🏿")
    ("📓 notebook" . "📓")
    ("📔 notebook with decorative cover" . "📔")
    ("🔩 nut and bolt" . "🔩")
    ("🛑 octagonal sign" . "🛑")
    ("🐙 octopus" . "🐙")
    ("🍢 oden" . "🍢")
    ("🏢 office building" . "🏢")
    ("🛢 oil drum" . "🛢")
    ("👌 ok hand sign" . "👌")
    ("👌🏻 ok hand sign - tone 1" . "👌🏻")
    ("👌🏼 ok hand sign - tone 2" . "👌🏼")
    ("👌🏽 ok hand sign - tone 3" . "👌🏽")
    ("👌🏾 ok hand sign - tone 4" . "👌🏾")
    ("👌🏿 ok hand sign - tone 5" . "👌🏿")
    ("🗝 old key" . "🗝")
    ("👴 older man" . "👴")
    ("👴🏻 older man - tone 1" . "👴🏻")
    ("👴🏼 older man - tone 2" . "👴🏼")
    ("👴🏽 older man - tone 3" . "👴🏽")
    ("👴🏾 older man - tone 4" . "👴🏾")
    ("👴🏿 older man - tone 5" . "👴🏿")
    ("👵 older woman" . "👵")
    ("👵🏻 older woman - tone 1" . "👵🏻")
    ("👵🏼 older woman - tone 2" . "👵🏼")
    ("👵🏽 older woman - tone 3" . "👵🏽")
    ("👵🏾 older woman - tone 4" . "👵🏾")
    ("👵🏿 older woman - tone 5" . "👵🏿")
    ("🕉 om symbol" . "🕉")
    ("🇴🇲 oman" . "🇴🇲")
    ("🔛 on with exclamation mark with left right arrow abo" . "🔛")
    ("🚘 oncoming automobile" . "🚘")
    ("🚍 oncoming bus" . "🚍")
    ("🚔 oncoming police car" . "🚔")
    ("🚖 oncoming taxi" . "🚖")
    ("📖 open book" . "📖")
    ("📂 open file folder" . "📂")
    ("👐 open hands sign" . "👐")
    ("👐🏻 open hands sign - tone 1" . "👐🏻")
    ("👐🏼 open hands sign - tone 2" . "👐🏼")
    ("👐🏽 open hands sign - tone 3" . "👐🏽")
    ("👐🏾 open hands sign - tone 4" . "👐🏾")
    ("👐🏿 open hands sign - tone 5" . "👐🏿")
    ("🔓 open lock" . "🔓")
    ("📭 open mailbox with lowered flag" . "📭")
    ("📬 open mailbox with raised flag" . "📬")
    ("⛎ ophiuchus" . "⛎")
    ("💿 optical disc" . "💿")
    ("📙 orange book" . "📙")
    ("☦ orthodox cross" . "☦")
    ("📤 outbox tray" . "📤")
    ("🦉 owl" . "🦉")
    ("🐂 ox" . "🐂")
    ("📦 package" . "📦")
    ("📄 page facing up" . "📄")
    ("📃 page with curl" . "📃")
    ("📟 pager" . "📟")
    ("🇵🇰 pakistan" . "🇵🇰")
    ("🇵🇼 palau" . "🇵🇼")
    ("🇵🇸 palestinian authority" . "🇵🇸")
    ("🌴 palm tree" . "🌴")
    ("🇵🇦 panama" . "🇵🇦")
    ("🥞 pancakes" . "🥞")
    ("🐼 panda face" . "🐼")
    ("📎 paperclip" . "📎")
    ("🇵🇬 papua new guinea" . "🇵🇬")
    ("🇵🇾 paraguay" . "🇵🇾")
    ("〽 part alternation mark" . "〽")
    ("🎉 party popper" . "🎉")
    ("🛳 passenger ship" . "🛳")
    ("🛂 passport control" . "🛂")
    ("🐾 paw prints" . "🐾")
    ("☮ peace symbol" . "☮")
    ("🍑 peach" . "🍑")
    ("🥜 peanuts" . "🥜")
    ("🍐 pear" . "🍐")
    ("🚶 pedestrian" . "🚶")
    ("🚶🏻 pedestrian - tone 1" . "🚶🏻")
    ("🚶🏼 pedestrian - tone 2" . "🚶🏼")
    ("🚶🏽 pedestrian - tone 3" . "🚶🏽")
    ("🚶🏾 pedestrian - tone 4" . "🚶🏾")
    ("🚶🏿 pedestrian - tone 5" . "🚶🏿")
    ("✏ pencil" . "✏")
    ("🐧 penguin" . "🐧")
    ("😔 pensive face" . "😔")
    ("🎭 performing arts" . "🎭")
    ("😣 persevering face" . "😣")
    ("🙇 person bowing deeply" . "🙇")
    ("🙇🏻 person bowing deeply - tone 1" . "🙇🏻")
    ("🙇🏼 person bowing deeply - tone 2" . "🙇🏼")
    ("🙇🏽 person bowing deeply - tone 3" . "🙇🏽")
    ("🙇🏾 person bowing deeply - tone 4" . "🙇🏾")
    ("🙇🏿 person bowing deeply - tone 5" . "🙇🏿")
    ("🤸 person doing cartwheel" . "🤸")
    ("🤸🏻 person doing cartwheel - tone 1" . "🤸🏻")
    ("🤸🏼 person doing cartwheel - tone 2" . "🤸🏼")
    ("🤸🏽 person doing cartwheel - tone 3" . "🤸🏽")
    ("🤸🏾 person doing cartwheel - tone 4" . "🤸🏾")
    ("🤸🏿 person doing cartwheel - tone 5" . "🤸🏿")
    ("🙍 person frowning" . "🙍")
    ("🙍🏻 person frowning - tone 1" . "🙍🏻")
    ("🙍🏼 person frowning - tone 2" . "🙍🏼")
    ("🙍🏽 person frowning - tone 3" . "🙍🏽")
    ("🙍🏾 person frowning - tone 4" . "🙍🏾")
    ("🙍🏿 person frowning - tone 5" . "🙍🏿")
    ("🙌 person raising both hands in celebration" . "🙌")
    ("🙌🏻 person raising both hands in celebration - tone 1" . "🙌🏻")
    ("🙌🏼 person raising both hands in celebration - tone 2" . "🙌🏼")
    ("🙌🏽 person raising both hands in celebration - tone 3" . "🙌🏽")
    ("🙌🏾 person raising both hands in celebration - tone 4" . "🙌🏾")
    ("🙌🏿 person raising both hands in celebration - tone 5" . "🙌🏿")
    ("⛹ person with ball" . "⛹")
    ("⛹🏻 person with ball - tone 1" . "⛹🏻")
    ("⛹🏼 person with ball - tone 2" . "⛹🏼")
    ("⛹🏽 person with ball - tone 3" . "⛹🏽")
    ("⛹🏾 person with ball - tone 4" . "⛹🏾")
    ("⛹🏿 person with ball - tone 5" . "⛹🏿")
    ("👱 person with blond hair" . "👱")
    ("👱🏻 person with blond hair - tone 1" . "👱🏻")
    ("👱🏼 person with blond hair - tone 2" . "👱🏼")
    ("👱🏽 person with blond hair - tone 3" . "👱🏽")
    ("👱🏾 person with blond hair - tone 4" . "👱🏾")
    ("👱🏿 person with blond hair - tone 5" . "👱🏿")
    ("🙏 person with folded hands" . "🙏")
    ("🙏🏻 person with folded hands - tone 1" . "🙏🏻")
    ("🙏🏼 person with folded hands - tone 2" . "🙏🏼")
    ("🙏🏽 person with folded hands - tone 3" . "🙏🏽")
    ("🙏🏾 person with folded hands - tone 4" . "🙏🏾")
    ("🙏🏿 person with folded hands - tone 5" . "🙏🏿")
    ("🙎 person with pouting face" . "🙎")
    ("🙎🏻 person with pouting face tone1" . "🙎🏻")
    ("🙎🏼 person with pouting face tone2" . "🙎🏼")
    ("🙎🏽 person with pouting face tone3" . "🙎🏽")
    ("🙎🏾 person with pouting face tone4" . "🙎🏾")
    ("🙎🏿 person with pouting face tone5" . "🙎🏿")
    ("💻 personal computer" . "💻")
    ("🇵🇪 peru" . "🇵🇪")
    ("⛏ pick" . "⛏")
    ("🐖 pig" . "🐖")
    ("🐷 pig face" . "🐷")
    ("🐽 pig nose" . "🐽")
    ("💩 pile of poo" . "💩")
    ("💊 pill" . "💊")
    ("🎍 pine decoration" . "🎍")
    ("🍍 pineapple" . "🍍")
    ("♓ pisces" . "♓")
    ("🔫 pistol" . "🔫")
    ("🇵🇳 pitcairn" . "🇵🇳")
    ("🛐 place of worship" . "🛐")
    ("🃏 playing card black joker" . "🃏")
    ("🇵🇱 poland" . "🇵🇱")
    ("🚓 police car" . "🚓")
    ("🚨 police cars revolving light" . "🚨")
    ("👮 police officer" . "👮")
    ("👮🏻 police officer - tone 1" . "👮🏻")
    ("👮🏼 police officer - tone 2" . "👮🏼")
    ("👮🏽 police officer - tone 3" . "👮🏽")
    ("👮🏾 police officer - tone 4" . "👮🏾")
    ("👮🏿 police officer - tone 5" . "👮🏿")
    ("🐩 poodle" . "🐩")
    ("🍿 popcorn" . "🍿")
    ("🇵🇹 portugal" . "🇵🇹")
    ("📯 postal horn" . "📯")
    ("📮 postbox" . "📮")
    ("🍲 pot of food" . "🍲")
    ("🚰 potable water symbol" . "🚰")
    ("🥔 potato" . "🥔")
    ("👝 pouch" . "👝")
    ("🍗 poultry leg" . "🍗")
    ("😾 pouting cat face" . "😾")
    ("😡 pouting face" . "😡")
    ("📿 prayer beads" . "📿")
    ("🤰 pregnant woman" . "🤰")
    ("🤰🏻 pregnant woman - tone 1" . "🤰🏻")
    ("🤰🏼 pregnant woman - tone 2" . "🤰🏼")
    ("🤰🏽 pregnant woman - tone 3" . "🤰🏽")
    ("🤰🏾 pregnant woman - tone 4" . "🤰🏾")
    ("🤰🏿 pregnant woman - tone 5" . "🤰🏿")
    ("🤴 prince" . "🤴")
    ("🤴🏻 prince - tone 1" . "🤴🏻")
    ("🤴🏼 prince - tone 2" . "🤴🏼")
    ("🤴🏽 prince - tone 3" . "🤴🏽")
    ("🤴🏾 prince - tone 4" . "🤴🏾")
    ("🤴🏿 prince - tone 5" . "🤴🏿")
    ("👸 princess" . "👸")
    ("👸🏻 princess - tone 1" . "👸🏻")
    ("👸🏼 princess - tone 2" . "👸🏼")
    ("👸🏽 princess - tone 3" . "👸🏽")
    ("👸🏾 princess - tone 4" . "👸🏾")
    ("👸🏿 princess - tone 5" . "👸🏿")
    ("🖨 printer" . "🖨")
    ("📢 public address loudspeaker" . "📢")
    ("🇵🇷 puerto rico" . "🇵🇷")
    ("💜 purple heart" . "💜")
    ("👛 purse" . "👛")
    ("📌 pushpin" . "📌")
    ("🚮 put litter in its place symbol" . "🚮")
    ("🇶🇦 qatar" . "🇶🇦")
    ("🐇 rabbit" . "🐇")
    ("🐰 rabbit face" . "🐰")
    ("🏎 racing car" . "🏎")
    ("🏍 racing motorcycle" . "🏍")
    ("📻 radio" . "📻")
    ("🔘 radio button" . "🔘")
    ("☢ radioactive sign" . "☢")
    ("🚃 railway car" . "🚃")
    ("🛤 railway track" . "🛤")
    ("🌈 rainbow" . "🌈")
    ("🤚 raised back of hand" . "🤚")
    ("🤚🏻 raised back of hand - tone 1" . "🤚🏻")
    ("🤚🏼 raised back of hand - tone 2" . "🤚🏼")
    ("🤚🏽 raised back of hand - tone 3" . "🤚🏽")
    ("🤚🏾 raised back of hand - tone 4" . "🤚🏾")
    ("🤚🏿 raised back of hand - tone 5" . "🤚🏿")
    ("✊ raised fist" . "✊")
    ("✊🏻 raised fist - tone 1" . "✊🏻")
    ("✊🏼 raised fist - tone 2" . "✊🏼")
    ("✊🏽 raised fist - tone 3" . "✊🏽")
    ("✊🏾 raised fist - tone 4" . "✊🏾")
    ("✊🏿 raised fist - tone 5" . "✊🏿")
    ("✋ raised hand" . "✋")
    ("✋🏻 raised hand - tone 1" . "✋🏻")
    ("✋🏼 raised hand - tone 2" . "✋🏼")
    ("✋🏽 raised hand - tone 3" . "✋🏽")
    ("✋🏾 raised hand - tone 4" . "✋🏾")
    ("✋🏿 raised hand - tone 5" . "✋🏿")
    ("🖐 raised hand with fingers splayed" . "🖐")
    ("🖐🏻 raised hand with fingers splayed - tone 1" . "🖐🏻")
    ("🖐🏼 raised hand with fingers splayed - tone 2" . "🖐🏼")
    ("🖐🏽 raised hand with fingers splayed - tone 3" . "🖐🏽")
    ("🖐🏾 raised hand with fingers splayed - tone 4" . "🖐🏾")
    ("🖐🏿 raised hand with fingers splayed - tone 5" . "🖐🏿")
    ("🖖 raised hand with part between middle and ring fingers" . "🖖")
    ("🖖🏻 raised hand with part between middle and ring fingers - tone 1" . "🖖🏻")
    ("🖖🏼 raised hand with part between middle and ring fingers - tone 2" . "🖖🏼")
    ("🖖🏽 raised hand with part between middle and ring fingers - tone 3" . "🖖🏽")
    ("🖖🏾 raised hand with part between middle and ring fingers - tone 4" . "🖖🏾")
    ("🖖🏿 raised hand with part between middle and ring fingers - tone 5" . "🖖🏿")
    ("🐏 ram" . "🐏")
    ("🐀 rat" . "🐀")
    ("🚙 recreational vehicle" . "🚙")
    ("🍎 red apple" . "🍎")
    ("🇦 regional indicator symbol letter a" . "🇦")
    ("🇧 regional indicator symbol letter b" . "🇧")
    ("🇨 regional indicator symbol letter c" . "🇨")
    ("🇩 regional indicator symbol letter d" . "🇩")
    ("🇪 regional indicator symbol letter e" . "🇪")
    ("🇫 regional indicator symbol letter f" . "🇫")
    ("🇬 regional indicator symbol letter g" . "🇬")
    ("🇭 regional indicator symbol letter h" . "🇭")
    ("🇮 regional indicator symbol letter i" . "🇮")
    ("🇯 regional indicator symbol letter j" . "🇯")
    ("🇰 regional indicator symbol letter k" . "🇰")
    ("🇱 regional indicator symbol letter l" . "🇱")
    ("🇲 regional indicator symbol letter m" . "🇲")
    ("🇳 regional indicator symbol letter n" . "🇳")
    ("🇴 regional indicator symbol letter o" . "🇴")
    ("🇵 regional indicator symbol letter p" . "🇵")
    ("🇶 regional indicator symbol letter q" . "🇶")
    ("🇷 regional indicator symbol letter r" . "🇷")
    ("🇸 regional indicator symbol letter s" . "🇸")
    ("🇹 regional indicator symbol letter t" . "🇹")
    ("🇺 regional indicator symbol letter u" . "🇺")
    ("🇻 regional indicator symbol letter v" . "🇻")
    ("🇼 regional indicator symbol letter w" . "🇼")
    ("🇽 regional indicator symbol letter x" . "🇽")
    ("🇾 regional indicator symbol letter y" . "🇾")
    ("🇿 regional indicator symbol letter z" . "🇿")
    ("® registered sign" . "®")
    ("😌 relieved face" . "😌")
    ("🎗 reminder ribbon" . "🎗")
    ("🚻 restroom" . "🚻")
    ("🖕 reversed hand with middle finger extended" . "🖕")
    ("🖕🏻 reversed hand with middle finger extended - tone 1" . "🖕🏻")
    ("🖕🏼 reversed hand with middle finger extended - tone 2" . "🖕🏼")
    ("🖕🏽 reversed hand with middle finger extended - tone 3" . "🖕🏽")
    ("🖕🏾 reversed hand with middle finger extended - tone 4" . "🖕🏾")
    ("🖕🏿 reversed hand with middle finger extended - tone 5" . "🖕🏿")
    ("💞 revolving hearts" . "💞")
    ("🦏 rhinoceros" . "🦏")
    ("🎀 ribbon" . "🎀")
    ("🍙 rice ball" . "🍙")
    ("🍘 rice cracker" . "🍘")
    ("🗯 right anger bubble" . "🗯")
    ("🤜🏻 right facing fist - tone 1" . "🤜🏻")
    ("🤜🏼 right facing fist - tone 2" . "🤜🏼")
    ("🤜🏽 right facing fist - tone 3" . "🤜🏽")
    ("🤜🏾 right facing fist - tone 4" . "🤜🏾")
    ("🤜🏿 right facing fist - tone 5" . "🤜🏿")
    ("🤜 right-facing fist" . "🤜")
    ("🔎 right-pointing magnifying glass" . "🔎")
    ("↪ rightwards arrow with hook" . "↪")
    ("💍 ring" . "💍")
    ("🍠 roasted sweet potato" . "🍠")
    ("🤖 robot face" . "🤖")
    ("🚀 rocket" . "🚀")
    ("🗞 rolled-up newspaper" . "🗞")
    ("🎢 roller coaster" . "🎢")
    ("🤣 rolling on the floor laughing" . "🤣")
    ("🇷🇴 romania" . "🇷🇴")
    ("🐓 rooster" . "🐓")
    ("🌹 rose" . "🌹")
    ("🏵 rosette" . "🏵")
    ("📍 round pushpin" . "📍")
    ("🚣 rowboat" . "🚣")
    ("🚣🏻 rowboat - tone 1" . "🚣🏻")
    ("🚣🏼 rowboat - tone 2" . "🚣🏼")
    ("🚣🏽 rowboat - tone 3" . "🚣🏽")
    ("🚣🏾 rowboat - tone 4" . "🚣🏾")
    ("🚣🏿 rowboat - tone 5" . "🚣🏿")
    ("🏉 rugby football" . "🏉")
    ("🏃 runner" . "🏃")
    ("🏃🏻 runner - tone 1" . "🏃🏻")
    ("🏃🏼 runner - tone 2" . "🏃🏼")
    ("🏃🏽 runner - tone 3" . "🏃🏽")
    ("🏃🏾 runner - tone 4" . "🏃🏾")
    ("🏃🏿 runner - tone 5" . "🏃🏿")
    ("🎽 running shirt with sash" . "🎽")
    ("🇷🇺 russia" . "🇷🇺")
    ("🇷🇼 rwanda" . "🇷🇼")
    ("🇷🇪 réunion" . "🇷🇪")
    ("♐ sagittarius" . "♐")
    ("⛵ sailboat" . "⛵")
    ("🇧🇱 saint barthélemy" . "🇧🇱")
    ("🇸🇭 saint helena" . "🇸🇭")
    ("🇰🇳 saint kitts and nevis" . "🇰🇳")
    ("🇱🇨 saint lucia" . "🇱🇨")
    ("🇲🇫 saint martin" . "🇲🇫")
    ("🇵🇲 saint pierre and miquelon" . "🇵🇲")
    ("🇻🇨 saint vincent and the grenadines" . "🇻🇨")
    ("🍶 sake bottle and cup" . "🍶")
    ("🇼🇸 samoa" . "🇼🇸")
    ("🇸🇲 san marino" . "🇸🇲")
    ("🛰 satellite" . "🛰")
    ("📡 satellite antenna" . "📡")
    ("🇸🇦 saudi arabia" . "🇸🇦")
    ("🎷 saxophone" . "🎷")
    ("⚖ scales" . "⚖")
    ("🏫 school" . "🏫")
    ("🎒 school satchel" . "🎒")
    ("🛴 scooter" . "🛴")
    ("🦂 scorpion" . "🦂")
    ("♏ scorpius" . "♏")
    ("📜 scroll" . "📜")
    ("💺 seat" . "💺")
    ("🥈 second place medal" . "🥈")
    ("🙈 see-no-evil monkey" . "🙈")
    ("🌱 seedling" . "🌱")
    ("🤳 selfie" . "🤳")
    ("🤳🏻 selfie - tone 1" . "🤳🏻")
    ("🤳🏼 selfie - tone 2" . "🤳🏼")
    ("🤳🏽 selfie - tone 3" . "🤳🏽")
    ("🤳🏾 selfie - tone 4" . "🤳🏾")
    ("🤳🏿 selfie - tone 5" . "🤳🏿")
    ("🇸🇳 senegal" . "🇸🇳")
    ("🇷🇸 serbia" . "🇷🇸")
    ("🥘 shallow pan of food" . "🥘")
    ("☘ shamrock" . "☘")
    ("🦈 shark" . "🦈")
    ("🍧 shaved ice" . "🍧")
    ("🐑 sheep" . "🐑")
    ("🛡 shield" . "🛡")
    ("⛩ shinto shrine" . "⛩")
    ("🚢 ship" . "🚢")
    ("🌠 shooting star" . "🌠")
    ("🛍 shopping bags" . "🛍")
    ("🛒 shopping trolley" . "🛒")
    ("🍰 shortcake" . "🍰")
    ("🚿 shower" . "🚿")
    ("🦐 shrimp" . "🦐")
    ("🤷 shrug" . "🤷")
    ("🤷🏻 shrug - tone 1" . "🤷🏻")
    ("🤷🏼 shrug - tone 2" . "🤷🏼")
    ("🤷🏽 shrug - tone 3" . "🤷🏽")
    ("🤷🏾 shrug - tone 4" . "🤷🏾")
    ("🤷🏿 shrug - tone 5" . "🤷🏿")
    ("🇸🇱 sierra leone" . "🇸🇱")
    ("🤘 sign of the horns" . "🤘")
    ("🤘🏻 sign of the horns - tone 1" . "🤘🏻")
    ("🤘🏼 sign of the horns - tone 2" . "🤘🏼")
    ("🤘🏽 sign of the horns - tone 3" . "🤘🏽")
    ("🤘🏾 sign of the horns - tone 4" . "🤘🏾")
    ("🤘🏿 sign of the horns - tone 5" . "🤘🏿")
    ("🗾 silhouette of japan" . "🗾")
    ("🇸🇬 singapore" . "🇸🇬")
    ("🇸🇽 sint maarten" . "🇸🇽")
    ("🔯 six pointed star with middle dot" . "🔯")
    ("🎿 ski and ski boot" . "🎿")
    ("⛷ skier" . "⛷")
    ("💀 skull" . "💀")
    ("☠ skull and crossbones" . "☠")
    ("🛌 sleeping accommodation" . "🛌")
    ("😴 sleeping face" . "😴")
    ("💤 sleeping symbol" . "💤")
    ("😪 sleepy face" . "😪")
    ("🕵 sleuth or spy" . "🕵")
    ("🕵🏻 sleuth or spy - tone 1" . "🕵🏻")
    ("🕵🏼 sleuth or spy - tone 2" . "🕵🏼")
    ("🕵🏽 sleuth or spy - tone 3" . "🕵🏽")
    ("🕵🏾 sleuth or spy - tone 4" . "🕵🏾")
    ("🕵🏿 sleuth or spy - tone 5" . "🕵🏿")
    ("🍕 slice of pizza" . "🍕")
    ("🙁 slightly frowning face" . "🙁")
    ("🙂 slightly smiling face" . "🙂")
    ("🎰 slot machine" . "🎰")
    ("🇸🇰 slovakia" . "🇸🇰")
    ("🇸🇮 slovenia" . "🇸🇮")
    ("🛩 small airplane" . "🛩")
    ("🔹 small blue diamond" . "🔹")
    ("🔸 small orange diamond" . "🔸")
    ("😻 smiling cat face with heart-shaped eyes" . "😻")
    ("😺 smiling cat face with open mouth" . "😺")
    ("😇 smiling face with halo" . "😇")
    ("😍 smiling face with heart-shaped eyes" . "😍")
    ("😈 smiling face with horns" . "😈")
    ("😃 smiling face with open mouth" . "😃")
    ("😅 smiling face with open mouth and cold sweat" . "😅")
    ("😄 smiling face with open mouth and smiling eyes" . "😄")
    ("😆 smiling face with open mouth and tightly-closed eyes" . "😆")
    ("😊 smiling face with smiling eyes" . "😊")
    ("😎 smiling face with sunglasses" . "😎")
    ("😏 smirking face" . "😏")
    ("🚬 smoking symbol" . "🚬")
    ("🐌 snail" . "🐌")
    ("🐍 snake" . "🐍")
    ("🤧 sneezing face" . "🤧")
    ("🏔 snow capped mountain" . "🏔")
    ("🏂 snowboarder" . "🏂")
    ("❄ snowflake" . "❄")
    ("☃ snowman" . "☃")
    ("⛄ snowman without snow" . "⛄")
    ("⚽ soccer ball" . "⚽")
    ("🍦 soft ice cream" . "🍦")
    ("🇸🇴 somalia" . "🇸🇴")
    ("🔜 soon with rightwards arrow above" . "🔜")
    ("🇿🇦 south africa" . "🇿🇦")
    ("↘ south east arrow" . "↘")
    ("🇬🇸 south georgia" . "🇬🇸")
    ("🇸🇸 south sudan" . "🇸🇸")
    ("↙ south west arrow" . "↙")
    ("🍝 spaghetti" . "🍝")
    ("🇪🇸 spain" . "🇪🇸")
    ("❇ sparkle" . "❇")
    ("✨ sparkles" . "✨")
    ("💖 sparkling heart" . "💖")
    ("🙊 speak-no-evil monkey" . "🙊")
    ("🔈 speaker" . "🔈")
    ("🔇 speaker with cancellation stroke" . "🔇")
    ("🔉 speaker with one sound wave" . "🔉")
    ("🔊 speaker with three sound waves" . "🔊")
    ("🗣 speaking head in silhouette" . "🗣")
    ("💬 speech balloon" . "💬")
    ("🚤 speedboat" . "🚤")
    ("🕷 spider" . "🕷")
    ("🕸 spider web" . "🕸")
    ("🗓 spiral calendar pad" . "🗓")
    ("🗒 spiral note pad" . "🗒")
    ("🐚 spiral shell" . "🐚")
    ("💦 splashing sweat symbol" . "💦")
    ("🥄 spoon" . "🥄")
    ("🏅 sports medal" . "🏅")
    ("🐳 spouting whale" . "🐳")
    ("🈹 squared cjk unified ideograph-5272" . "🈹")
    ("🈴 squared cjk unified ideograph-5408" . "🈴")
    ("🈺 squared cjk unified ideograph-55b6" . "🈺")
    ("🈯 squared cjk unified ideograph-6307" . "🈯")
    ("🈷 squared cjk unified ideograph-6708" . "🈷")
    ("🈶 squared cjk unified ideograph-6709" . "🈶")
    ("🈵 squared cjk unified ideograph-6e80" . "🈵")
    ("🈚 squared cjk unified ideograph-7121" . "🈚")
    ("🈸 squared cjk unified ideograph-7533" . "🈸")
    ("🈲 squared cjk unified ideograph-7981" . "🈲")
    ("🈳 squared cjk unified ideograph-7a7a" . "🈳")
    ("🆑 squared cl" . "🆑")
    ("🆒 squared cool" . "🆒")
    ("🆓 squared free" . "🆓")
    ("🆔 squared id" . "🆔")
    ("🈁 squared katakana koko" . "🈁")
    ("🈂 squared katakana sa" . "🈂")
    ("🆕 squared new" . "🆕")
    ("🆖 squared ng" . "🆖")
    ("🆗 squared ok" . "🆗")
    ("🆘 squared sos" . "🆘")
    ("🆙 squared up with exclamation mark" . "🆙")
    ("🆚 squared vs" . "🆚")
    ("🦑 squid" . "🦑")
    ("🇱🇰 sri lanka" . "🇱🇰")
    ("🏟 stadium" . "🏟")
    ("☪ star and crescent" . "☪")
    ("✡ star of david" . "✡")
    ("🚉 station" . "🚉")
    ("🗽 statue of liberty" . "🗽")
    ("🚂 steam locomotive" . "🚂")
    ("🍜 steaming bowl" . "🍜")
    ("⏱ stopwatch" . "⏱")
    ("📏 straight ruler" . "📏")
    ("🍓 strawberry" . "🍓")
    ("🎙 studio microphone" . "🎙")
    ("🥙 stuffed flatbread" . "🥙")
    ("🇸🇩 sudan" . "🇸🇩")
    ("⛅ sun behind cloud" . "⛅")
    ("🌞 sun with face" . "🌞")
    ("🌻 sunflower" . "🌻")
    ("🌅 sunrise" . "🌅")
    ("🌄 sunrise over mountains" . "🌄")
    ("🌇 sunset over buildings" . "🌇")
    ("🏄 surfer" . "🏄")
    ("🏄🏻 surfer - tone 1" . "🏄🏻")
    ("🏄🏼 surfer - tone 2" . "🏄🏼")
    ("🏄🏽 surfer - tone 3" . "🏄🏽")
    ("🏄🏾 surfer - tone 4" . "🏄🏾")
    ("🏄🏿 surfer - tone 5" . "🏄🏿")
    ("🇸🇷 suriname" . "🇸🇷")
    ("🍣 sushi" . "🍣")
    ("🚟 suspension railway" . "🚟")
    ("🇸🇯 svalbard and jan mayen" . "🇸🇯")
    ("🇸🇿 swaziland" . "🇸🇿")
    ("🇸🇪 sweden" . "🇸🇪")
    ("🏊 swimmer" . "🏊")
    ("🏊🏻 swimmer - tone 1" . "🏊🏻")
    ("🏊🏼 swimmer - tone 2" . "🏊🏼")
    ("🏊🏽 swimmer - tone 3" . "🏊🏽")
    ("🏊🏾 swimmer - tone 4" . "🏊🏾")
    ("🏊🏿 swimmer - tone 5" . "🏊🏿")
    ("🇨🇭 switzerland" . "🇨🇭")
    ("🕍 synagogue" . "🕍")
    ("🇸🇾 syria" . "🇸🇾")
    ("💉 syringe" . "💉")
    ("🇸🇹 são tomé and príncipe" . "🇸🇹")
    ("👕 t-shirt" . "👕")
    ("🏓 table tennis paddle and ball" . "🏓")
    ("🌮 taco" . "🌮")
    ("🇹🇯 tajikistan" . "🇹🇯")
    ("🎋 tanabata tree" . "🎋")
    ("🍊 tangerine" . "🍊")
    ("🇹🇿 tanzania" . "🇹🇿")
    ("♉ taurus" . "♉")
    ("🚕 taxi" . "🚕")
    ("🍵 teacup without handle" . "🍵")
    ("📆 tear-off calendar" . "📆")
    ("📞 telephone receiver" . "📞")
    ("🔭 telescope" . "🔭")
    ("📺 television" . "📺")
    ("🎾 tennis racquet and ball" . "🎾")
    ("⛺ tent" . "⛺")
    ("🇹🇭 thailand" . "🇹🇭")
    ("🇧🇸 the bahamas" . "🇧🇸")
    ("🇰🇲 the comoros" . "🇰🇲")
    ("🇨🇿 the czech republic" . "🇨🇿")
    ("🇨🇩 the democratic republic of the congo" . "🇨🇩")
    ("🇩🇴 the dominican republic" . "🇩🇴")
    ("🇬🇲 the gambia" . "🇬🇲")
    ("🇲🇭 the marshall islands" . "🇲🇭")
    ("🇳🇱 the netherlands" . "🇳🇱")
    ("🇵🇭 the philippines" . "🇵🇭")
    ("🇹🇼 the republic of china" . "🇹🇼")
    ("🇨🇬 the republic of the congo" . "🇨🇬")
    ("🇸🇨 the seychelles" . "🇸🇨")
    ("🇸🇧 the solomon islands" . "🇸🇧")
    ("🇦🇪 the united arab emirates" . "🇦🇪")
    ("🇻🇦 the vatican city" . "🇻🇦")
    ("🌡 thermometer" . "🌡")
    ("🤔 thinking face" . "🤔")
    ("🥉 third place medal" . "🥉")
    ("💭 thought balloon" . "💭")
    ("🖱 three button mouse" . "🖱")
    ("👎 thumbs down sign" . "👎")
    ("👎🏻 thumbs down sign - tone 1" . "👎🏻")
    ("👎🏼 thumbs down sign - tone 2" . "👎🏼")
    ("👎🏽 thumbs down sign - tone 3" . "👎🏽")
    ("👎🏾 thumbs down sign - tone 4" . "👎🏾")
    ("👎🏿 thumbs down sign - tone 5" . "👎🏿")
    ("👍 thumbs up sign" . "👍")
    ("👍🏻 thumbs up sign - tone 1" . "👍🏻")
    ("👍🏼 thumbs up sign - tone 2" . "👍🏼")
    ("👍🏽 thumbs up sign - tone 3" . "👍🏽")
    ("👍🏾 thumbs up sign - tone 4" . "👍🏾")
    ("👍🏿 thumbs up sign - tone 5" . "👍🏿")
    ("⛈ thunder cloud and rain" . "⛈")
    ("🎫 ticket" . "🎫")
    ("🐅 tiger" . "🐅")
    ("🐯 tiger face" . "🐯")
    ("⏲ timer clock" . "⏲")
    ("🇹🇱 timor-leste" . "🇹🇱")
    ("😫 tired face" . "😫")
    ("🇹🇬 togo" . "🇹🇬")
    ("🚽 toilet" . "🚽")
    ("🇹🇰 tokelau" . "🇹🇰")
    ("🗼 tokyo tower" . "🗼")
    ("🍅 tomato" . "🍅")
    ("🇹🇴 tonga" . "🇹🇴")
    ("👅 tongue" . "👅")
    ("🎩 top hat" . "🎩")
    ("🔝 top with upwards arrow above" . "🔝")
    ("🖲 trackball" . "🖲")
    ("🚜 tractor" . "🚜")
    ("™ trade mark sign" . "™")
    ("🚆 train" . "🚆")
    ("🚊 tram" . "🚊")
    ("🚋 tram car" . "🚋")
    ("🚩 triangular flag on post" . "🚩")
    ("📐 triangular ruler" . "📐")
    ("🔱 trident emblem" . "🔱")
    ("🇹🇹 trinidad and tobago" . "🇹🇹")
    ("🇹🇦 tristan da cunha" . "🇹🇦")
    ("🚎 trolleybus" . "🚎")
    ("🏆 trophy" . "🏆")
    ("🍹 tropical drink" . "🍹")
    ("🐠 tropical fish" . "🐠")
    ("🎺 trumpet" . "🎺")
    ("🌷 tulip" . "🌷")
    ("🥃 tumbler glass" . "🥃")
    ("🇹🇳 tunisia" . "🇹🇳")
    ("🇹🇷 turkey" . "🇹🇷")
    ("🦃 turkey" . "🦃")
    ("🇹🇲 turkmenistan" . "🇹🇲")
    ("🇹🇨 turks and caicos islands" . "🇹🇨")
    ("🐢 turtle" . "🐢")
    ("🇹🇻 tuvalu" . "🇹🇻")
    ("🔀 twisted rightwards arrows" . "🔀")
    ("💕 two hearts" . "💕")
    ("👬 two men holding hands" . "👬")
    ("👭 two women holding hands" . "👭")
    ("🇻🇮 u.s. virgin islands" . "🇻🇮")
    ("🇺🇬 uganda" . "🇺🇬")
    ("🇺🇦 ukraine" . "🇺🇦")
    ("☂ umbrella" . "☂")
    ("⛱ umbrella on ground" . "⛱")
    ("☔ umbrella with rain drops" . "☔")
    ("😒 unamused face" . "😒")
    ("🦄 unicorn face" . "🦄")
    ("🇺🇸 united states" . "🇺🇸")
    ("🇺🇲 united states minor outlying islands" . "🇺🇲")
    ("↕ up down arrow" . "↕")
    ("🔺 up-pointing red triangle" . "🔺")
    ("🔼 up-pointing small red triangle" . "🔼")
    ("🙃 upside-down face" . "🙃")
    ("⬆ upwards black arrow" . "⬆")
    ("🇺🇾 uruguay" . "🇺🇾")
    ("🇺🇿 uzbekistan" . "🇺🇿")
    ("🇻🇺 vanuatu" . "🇻🇺")
    ("🇻🇪 venezuela" . "🇻🇪")
    ("🚦 vertical traffic light" . "🚦")
    ("📳 vibration mode" . "📳")
    ("✌ victory hand" . "✌")
    ("✌🏻 victory hand - tone 1" . "✌🏻")
    ("✌🏼 victory hand - tone 2" . "✌🏼")
    ("✌🏽 victory hand - tone 3" . "✌🏽")
    ("✌🏾 victory hand - tone 4" . "✌🏾")
    ("✌🏿 victory hand - tone 5" . "✌🏿")
    ("📹 video camera" . "📹")
    ("🎮 video game" . "🎮")
    ("📼 videocassette" . "📼")
    ("🇻🇳 vietnam" . "🇻🇳")
    ("🎻 violin" . "🎻")
    ("♍ virgo" . "♍")
    ("🌋 volcano" . "🌋")
    ("🏐 volleyball" . "🏐")
    ("🇼🇫 wallis and futuna" . "🇼🇫")
    ("🌘 waning crescent moon symbol" . "🌘")
    ("🌖 waning gibbous moon symbol" . "🌖")
    ("⚠ warning sign" . "⚠")
    ("🗑 wastebasket" . "🗑")
    ("⌚ watch" . "⌚")
    ("🐃 water buffalo" . "🐃")
    ("🚾 water closet" . "🚾")
    ("🤽 water polo" . "🤽")
    ("🤽🏻 water polo - tone 1" . "🤽🏻")
    ("🤽🏼 water polo - tone 2" . "🤽🏼")
    ("🤽🏽 water polo - tone 3" . "🤽🏽")
    ("🤽🏾 water polo - tone 4" . "🤽🏾")
    ("🤽🏿 water polo - tone 5" . "🤽🏿")
    ("🌊 water wave" . "🌊")
    ("🍉 watermelon" . "🍉")
    ("🏴 waving black flag" . "🏴")
    ("👋 waving hand sign" . "👋")
    ("👋🏻 waving hand sign - tone 1" . "👋🏻")
    ("👋🏼 waving hand sign - tone 2" . "👋🏼")
    ("👋🏽 waving hand sign - tone 3" . "👋🏽")
    ("👋🏾 waving hand sign - tone 4" . "👋🏾")
    ("👋🏿 waving hand sign - tone 5" . "👋🏿")
    ("🏳 waving white flag" . "🏳")
    ("〰 wavy dash" . "〰")
    ("🌒 waxing crescent moon symbol" . "🌒")
    ("🌔 waxing gibbous moon symbol" . "🌔")
    ("🙀 weary cat face" . "🙀")
    ("😩 weary face" . "😩")
    ("💒 wedding" . "💒")
    ("🏋 weight lifter" . "🏋")
    ("🏋🏻 weight lifter - tone 1" . "🏋🏻")
    ("🏋🏼 weight lifter - tone 2" . "🏋🏼")
    ("🏋🏽 weight lifter - tone 3" . "🏋🏽")
    ("🏋🏾 weight lifter - tone 4" . "🏋🏾")
    ("🏋🏿 weight lifter - tone 5" . "🏋🏿")
    ("🇪🇭 western sahara" . "🇪🇭")
    ("🐋 whale" . "🐋")
    ("☸ wheel of dharma" . "☸")
    ("♿ wheelchair symbol" . "♿")
    ("👇 white down pointing backhand index" . "👇")
    ("👇🏻 white down pointing backhand index - tone 1" . "👇🏻")
    ("👇🏼 white down pointing backhand index - tone 2" . "👇🏼")
    ("👇🏽 white down pointing backhand index - tone 3" . "👇🏽")
    ("👇🏾 white down pointing backhand index - tone 4" . "👇🏾")
    ("👇🏿 white down pointing backhand index - tone 5" . "👇🏿")
    ("❕ white exclamation mark ornament" . "❕")
    ("💮 white flower" . "💮")
    ("☹ white frowning face" . "☹")
    ("✅ white heavy check mark" . "✅")
    ("⬜ white large square" . "⬜")
    ("👈 white left pointing backhand index" . "👈")
    ("👈🏻 white left pointing backhand index - tone 1" . "👈🏻")
    ("👈🏼 white left pointing backhand index - tone 2" . "👈🏼")
    ("👈🏽 white left pointing backhand index - tone 3" . "👈🏽")
    ("👈🏾 white left pointing backhand index - tone 4" . "👈🏾")
    ("👈🏿 white left pointing backhand index - tone 5" . "👈🏿")
    ("◽ white medium small square" . "◽")
    ("◻ white medium square" . "◻")
    ("⭐ white medium star" . "⭐")
    ("❔ white question mark ornament" . "❔")
    ("👉 white right pointing backhand index" . "👉")
    ("👉🏻 white right pointing backhand index - tone 1" . "👉🏻")
    ("👉🏼 white right pointing backhand index - tone 2" . "👉🏼")
    ("👉🏽 white right pointing backhand index - tone 3" . "👉🏽")
    ("👉🏾 white right pointing backhand index - tone 4" . "👉🏾")
    ("👉🏿 white right pointing backhand index - tone 5" . "👉🏿")
    ("▫ white small square" . "▫")
    ("☺ white smiling face" . "☺")
    ("🔳 white square button" . "🔳")
    ("🌥 white sun behind cloud" . "🌥")
    ("🌦 white sun behind cloud with rain" . "🌦")
    ("🌤 white sun with small cloud" . "🌤")
    ("👆 white up pointing backhand index" . "👆")
    ("👆🏻 white up pointing backhand index - tone 1" . "👆🏻")
    ("👆🏼 white up pointing backhand index - tone 2" . "👆🏼")
    ("👆🏽 white up pointing backhand index - tone 3" . "👆🏽")
    ("👆🏾 white up pointing backhand index - tone 4" . "👆🏾")
    ("👆🏿 white up pointing backhand index - tone 5" . "👆🏿")
    ("☝ white up pointing index" . "☝")
    ("☝🏻 white up pointing index - tone 1" . "☝🏻")
    ("☝🏼 white up pointing index - tone 2" . "☝🏼")
    ("☝🏽 white up pointing index - tone 3" . "☝🏽")
    ("☝🏾 white up pointing index - tone 4" . "☝🏾")
    ("☝🏿 white up pointing index - tone 5" . "☝🏿")
    ("🥀 wilted flower" . "🥀")
    ("🌬 wind blowing face" . "🌬")
    ("🎐 wind chime" . "🎐")
    ("🍷 wine glass" . "🍷")
    ("😉 winking face" . "😉")
    ("🐺 wolf face" . "🐺")
    ("👩 woman" . "👩")
    ("👩🏻 woman - tone 1" . "👩🏻")
    ("👩🏼 woman - tone 2" . "👩🏼")
    ("👩🏽 woman - tone 3" . "👩🏽")
    ("👩🏾 woman - tone 4" . "👩🏾")
    ("👩🏿 woman - tone 5" . "👩🏿")
    ("👯 woman with bunny ears" . "👯")
    ("👢 womans boots" . "👢")
    ("👚 womans clothes" . "👚")
    ("👒 womans hat" . "👒")
    ("👡 womans sandal" . "👡")
    ("🚺 womens symbol" . "🚺")
    ("🗺 world map" . "🗺")
    ("😟 worried face" . "😟")
    ("🎁 wrapped present" . "🎁")
    ("🔧 wrench" . "🔧")
    ("🤼 wrestlers" . "🤼")
    ("🤼🏻 wrestlers - tone 1" . "🤼🏻")
    ("🤼🏼 wrestlers - tone 2" . "🤼🏼")
    ("🤼🏽 wrestlers - tone 3" . "🤼🏽")
    ("🤼🏾 wrestlers - tone 4" . "🤼🏾")
    ("🤼🏿 wrestlers - tone 5" . "🤼🏿")
    ("✍ writing hand" . "✍")
    ("✍🏻 writing hand - tone 1" . "✍🏻")
    ("✍🏼 writing hand - tone 2" . "✍🏼")
    ("✍🏽 writing hand - tone 3" . "✍🏽")
    ("✍🏾 writing hand - tone 4" . "✍🏾")
    ("✍🏿 writing hand - tone 5" . "✍🏿")
    ("💛 yellow heart" . "💛")
    ("🇾🇪 yemen" . "🇾🇪")
    ("☯ yin yang" . "☯")
    ("🇿🇲 zambia" . "🇿🇲")
    ("🇿🇼 zimbabwe" . "🇿🇼")
    ("🤐 zipper-mouth face" . "🤐")
    ("🇦🇽 åland islands" . "🇦🇽")
    )
  "Emoji list for `masu/insert-custom-emoji`. Format: (DISPLAY-STRING . EMOJI).")

(defun masu/insert-custom-emoji ()
  "Insert an emoji from `masu/custom-emojis`."
  (interactive)
  (let* ((choice (completing-read "Emoji: " masu/custom-emojis nil t))
         (emoji (cdr (assoc choice masu/custom-emojis))))
    (when emoji (insert emoji))))

(provide 'masu-emojis)
;;; masu-emojis.el ends here
